// One flat catalogue per locale. Bundled, never fetched — the app has no network after install.
// English is the source of truth; a missing Thai key falls back to English and is reported by
// `node tools/build.mjs` at build time, never at runtime.
//
// Rules this file must keep (from the design canvas):
//   - No sentence is built by concatenation. Every string is whole, with {named} placeholders.
//   - No markup inside a string. Emphasis comes from the component.
//   - Thai never uses Thai numerals. Grid weights and word indices must match a metal plate.
//   - The 24 BIP39 words, the fingerprint, the release hash and the .dmv filename are never
//     translated.

export const en = {
  "app.name": "Dying Message",
  "app.origin": "dyngmsg.home1ab.com",

  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.continue": "Continue",
  "common.done": "Done",
  "common.close": "Close",
  "common.keepit": "Keep it",
  "common.checkagain": "Check again",
  "common.guide": "Read the guide",
  "common.words24": "canyon  orbit  velvet",

  // ---- install gate
  "install.strip": "Do not set up your vault here. Anything you create in this browser tab stays in the tab and will not carry over to the installed app.",
  "install.title": "This app has to be installed",
  "install.ios.body": "It keeps your messages inside the installed app, where the phone protects them properly and cannot quietly clear them. In a browser tab, none of that holds.",
  "install.ios.safarionly": "Safari only. Chrome, Firefox and Edge on iPhone cannot install this, whatever their menus suggest. Open this page in Safari first.",
  "install.ios.s1.t": "Tap Share at the bottom of Safari",
  "install.ios.s1.b": "The square with an arrow coming out of the top. On an iPad it sits in the top bar instead.",
  "install.ios.s2.t": "Choose “Add to Home Screen”",
  "install.ios.s2.b": "It is some way down the grey list. Scroll past the sharing row to find it.",
  "install.ios.s3.t": "Tap Add, then open it from your home screen",
  "install.ios.s3.b": "A new icon appears. Everything from here on happens in that icon, never in Safari.",
  "install.android.body": "Chrome can do it in one tap. The installed app gets storage the system will not clear on its own, which a tab does not.",
  "install.android.button": "Install Dying Message",
  "install.android.fallback": "if that button does nothing",
  "install.android.s1.t": "Open the ⋮ menu, top right",
  "install.android.s1.b": "Chrome’s three dots, beside the address bar.",
  "install.android.s2.t": "Choose “Install app” or “Add to Home screen”",
  "install.android.s2.b": "The wording changes between Chrome versions. Either one is right here.",
  "install.android.s3.t": "Confirm, then open it from your home screen",
  "install.android.s3.b": "The new icon opens without an address bar. That is how you know it installed properly.",
  "install.android.shortcut": "Some Android browsers offer “Add to Home screen” but create a bookmark shortcut rather than a real installed app. If the icon opens with a browser address bar visible, it is a shortcut — delete it and use Chrome.",
  "install.desktop.body": "Installed, it gets storage the browser has promised to keep, and it opens in its own window with no address bar, no extensions and no other tabs. In an ordinary tab none of that is true, and a vault made here can be cleared by a routine browsing-data sweep.",
  "install.desktop.s1.t": "Find the install icon in the address bar",
  "install.desktop.s1.b": "Right-hand end, beside the bookmark star. Chrome and Edge both show one.",
  "install.desktop.s2.t": "Click it and confirm “Install”",
  "install.desktop.s2.b": "The app opens in its own window, with no tabs and no address bar.",
  "install.desktop.s3.t": "Close this tab and work only in that window",
  "install.desktop.s3.b": "Anything you do in the browser tab is separate and will be lost.",
  "install.desktop.where.t": "Where to look",
  "install.desktop.where.b": "The install icon sits at the right-hand end of the address bar. In Chrome it is a small screen with a downward arrow; in Edge it is a plus inside a square. If it is not there, the page has not finished loading, or this browser does not support installing.",
  "install.desktop.safari.t": "Safari on Mac cannot do this",
  "install.desktop.safari.b": "Use Chrome or Edge on a desktop. Safari’s “Add to Dock” does create a standalone window, but its storage behaves differently enough that this app does not accept it.",
  "install.eu.title": "Installing may not work on this iPhone",
  "install.eu.body": "In some regions, iOS allows browsers other than Safari to render web pages, and apps added to the home screen from those browsers may open as an ordinary tab rather than as a real installed app.",
  "install.eu.tell.t": "How to tell",
  "install.eu.tell.b": "Add it to your home screen, then open that icon. If you can see an address bar or browser controls, it did not install — it is a bookmark, and a vault made inside it can be cleared without warning.",
  "install.eu.instead.t": "What to do instead",
  "install.eu.o1": "Open this page in Safari and install from there — Safari installs properly in every region.",
  "install.eu.o2": "If your device only offers the other browser, use a different phone, or a desktop, for the vault you intend to keep.",
  "install.eu.o3": "Whatever you do, do not create a vault, write messages, or write down a phrase from inside a tab. It will be lost, and you will believe it was safe.",
  "install.eu.nofix": "This is not a restriction the app can work around, and it is not worth working around. The whole design assumes storage the system has promised to keep. Without that promise, the vault is a vault in name only.",
  "install.eu.showsafari": "Show me the Safari steps",
  "install.noicons.t": "This copy of the app is incomplete",
  "install.noicons.b": "Its icons are missing from the server, and a browser will not offer to install a site whose icons it cannot load. Adding it to the home screen now would create a bookmark shortcut, not an installed app — and a vault made inside a shortcut can be cleared without warning. Whoever published this needs to upload the icons folder.",
  "install.insecure.t": "This page is not being served securely",
  "install.insecure.b": "The address must start with https, with a valid certificate. Over plain http a browser will not install an app, will not run a service worker, and will not keep storage — so there is nothing here that could safely hold a vault. Whoever published this needs to enable HTTPS on the domain.",
  "install.swfailed.t": "The app could not start its service worker",
  "install.swfailed.b": "A browser will not install a site whose service worker fails to register, and without one the app cannot work offline. The reason the browser gave is below.",
  "install.waiting": "This browser has not offered to install the app. That usually means the page has not finished loading, or something it needs is missing from the server. The manual steps below still work if the install is genuinely available.",
  "install.already.t": "Already installed?",
  "install.already.b": "Close this tab and open Dying Message from your home screen. Your vault is in there, not here.",
  "install.already.desktop": "Close this tab and open Dying Message from your applications, dock or start menu. Your vault is in there, not here.",
  "install.foot": "dyngmsg.home1ab.com · nothing is sent to this address after the first load",

  // ---- boot
  "boot.explain": "Every check below runs before anything opens. If one of them fails, the app stops and says so rather than carrying on and losing something.",
  "boot.c.secure": "Secure connection",
  "boot.c.selftest": "Cryptography self-test",
  "boot.c.standalone": "Running as an installed app",
  "boot.c.storage": "Storage available",
  "boot.c.persist": "Storage persistence granted",
  "boot.c.read": "Reading the vault",
  "boot.c.seals": "Checking each entry’s seal",
  "boot.yes": "yes",
  "boot.no": "no",
  "boot.idb": "IndexedDB",
  "boot.deferred": "checked at unlock",

  "crash.title": "Something in the app went wrong",
  "crash.body": "Your vault has not been changed. Nothing here is lost — this is the app failing, not the data. If you can, write down or photograph the lines below before reloading: they are the only record, because this app reports nothing to anyone.",
  "crash.where": "What failed",
  "crash.reload": "Reload the app",
  "crash.safe": "No message, phrase or passphrase is shown below, and none is ever written to this screen.",
  "selftest.title": "This build of the app is not sound",
  "selftest.body": "Argon2id did not produce the answer the standard says it must. That means the code on this device has been changed or damaged. The app will not touch your vault in this state.",
  "selftest.what": "Reinstall from dyngmsg.home1ab.com and compare the release hash against the one published there. Your vault and any backup file are untouched — this is about the app, not the data.",
  "insecure.title": "This app is not being served securely",
  "insecure.body": "The address must start with https, with a valid certificate. Over plain http the browser will not promise to keep anything this app stores, so a vault created here can be erased at any moment without warning — and you would not find out until the day you needed to read it.",
  "insecure.what": "What is missing",
  "insecure.w1": "Persistent storage cannot even be requested, so nothing is protected from being cleared.",
  "insecure.w2": "The service worker cannot run, so the app cannot work offline.",
  "insecure.w3": "The browser will not install the app, only make a bookmark shortcut.",
  "insecure.fix": "This is for whoever published the app to fix, on the domain. Nothing you can change on this device will make an http address safe to keep a vault on.",
  "nostore.title": "This device will not let the app store anything",
  "nostore.body": "The app cannot open or create a vault here. Nothing has been damaged — it simply has nowhere to keep what you write, so it will not pretend otherwise.",
  "nostore.causes.t": "Usually one of these",
  "nostore.c1": "A private or incognito window — close it and open the app normally.",
  "nostore.c2": "Site data blocked for this address in your browser’s settings.",
  "nostore.c3": "A device-management policy, common on work phones and laptops.",
  "nostore.c4": "The phone is genuinely out of space.",
  "nostore.elsewhere": "If you already have a vault on another device, it is untouched. This screen says nothing about it.",
  "nostore.diag": "Diagnostic",
  "nostore.noway": "There is no way past this screen, and that is deliberate.",

  "twocopies.strip": "There is a second vault in your browser. This installed app is not showing it.",
  "twocopies.title": "You have two separate copies",
  "twocopies.body": "A vault was created in the browser before the app was installed. The browser and the installed app keep their storage apart, so what you made there is not here — and it is not lost either.",
  "twocopies.here": "Here",
  "twocopies.here.s": "Installed app",
  "twocopies.browser": "Browser",
  "twocopies.how": "To bring the browser one over: open the app in Safari, export a backup from there, then restore that file here. Both vaults keep their own phrase, and merging is refused — you would end up with two, side by side.",
  "twocopies.continue": "Continue with the vault here",
  "twocopies.persistent": "This banner reappears at every launch until the browser copy is dealt with. It is not dismissible.",

  "damaged.title": "Part of this vault is damaged",
  "damaged.body": "{bad} of {total} entries no longer match their seal. That happens when storage is interrupted mid-write — a phone running out of space, or being force-quit during a save. It is not a sign that anyone has been in here.",
  "damaged.ok": "Seal intact",
  "damaged.bad": "Does not match its seal",
  "damaged.restorefirst": "The intact entries are still readable and have not been touched. Restoring a backup adds back whatever that file holds without disturbing them, so restoring is always worth trying first.",
  "damaged.norepair": "A damaged entry cannot be repaired. Encryption has no way to guess what a changed byte used to be — if no backup holds it, it is gone.",
  "damaged.restore": "Restore from a backup file",
  "damaged.continue": "Continue with the ones that are intact",
  "damaged.stay": "Damaged entries stay in the list, marked, until you delete them. Nothing is removed on your behalf.",

  "update.title": "A new version is waiting",
  "update.body": "It has been downloaded but not applied. This app never updates itself behind your back — the code that holds your messages does not change without you saying so.",
  "update.running": "Running now",
  "update.waiting": "Waiting",
  "update.hash": "Release hash",
  "update.verify": "Compare the hash against the one published on the project page before approving. If they do not match, decline and do not use the app until you know why.",
  "update.approve": "Approve and restart",
  "update.later": "Later — keep this version",
  "update.safe": "Your vault is not touched either way. Updating replaces the app, never the data.",
  "update.none": "No update is waiting. This app is running the newest code it has.",

  // ---- language
  "lang.step": "Step 0 of 4",
  "lang.title": "Language",
  "lang.body": "This phone is set to Thai, so the app is too. Confirm before you go on — what follows is permanent, and it should be read in the language you read best.",
  "lang.th": "ไทย",
  "lang.th.s": "Thai — detected from this device",
  "lang.en": "English",
  "lang.en.s": "อังกฤษ",
  "lang.wordsnote": "The 24 words are always English, in both languages. They are transcribed by hand and typed back letter by letter, so they never change.",
  "lang.changeable": "Changeable at any time in Settings",
  "lang.follow": "Follow this device",
  "lang.inuse": "Currently in use",
  "lang.whatchanges": "What changes",
  "lang.ch1": "Every label, heading, warning and error in the app",
  "lang.ch2": "The guide, the install steps and the printed sheet’s instructions",
  "lang.ch3": "Date format — 2 มีนาคม 2569 in Thai, 2 March 2026 in English",
  "lang.ch4": "The 24 words — always English",
  "lang.ch5": "Your own messages — stored exactly as you typed them",
  "lang.ch6": "The fingerprint, release hash and backup filename",
  "lang.immediate": "Switching takes effect immediately and touches nothing that is stored. The vault, the messages inside it and the phrase that opens them are the same in either language — a vault created in Thai opens on an English phone, and the other way round.",
  "lang.heirs": "Whoever inherits your phrase may not read the language you chose. Say which language the app is in when you leave the words behind.",

  // ---- genesis C1
  "genesis.warn.title": "Before you begin",
  "genesis.warn.sub": "Five things about this app are permanent. Read each one and mark it.",
  "genesis.w1.t": "Nothing here can be recovered",
  "genesis.w1.b": "If the 24 words are lost, every message in this vault is unreadable for good. There is no reset, no support address, no second copy held anywhere.",
  "genesis.w2.t": "This app cannot stop screenshots",
  "genesis.w2.b": "Your phone can photograph the words on the next screens. That image goes to your photo library, and usually to a cloud backup after that.",
  "genesis.w3.t": "Deleting the icon deletes the vault",
  "genesis.w3.b": "The messages live inside the installed app. Removing it from the home screen removes them. Keep a backup file elsewhere.",
  "genesis.w4.t": "Do not reuse a wallet phrase",
  "genesis.w4.b": "If these words also guard money, anyone who is meant to read your messages could spend it. Let this app make you a fresh phrase.",
  "genesis.w5.t": "It is slow on purpose",
  "genesis.w5.b": "Opening the vault takes several seconds every single time. That delay is what makes guessing the phrase impractical.",
  "genesis.warn.count": "{n} of {total} marked",
  "genesis.warn.create": "Create my vault",
  "genesis.warn.guidefirst": "Read the full guide first",
  "genesis.warn.import": "Restore a vault from a backup file",
  "vaults.title": "Your vaults",
  "vaults.body": "Each vault has its own 24 words and its own sealed messages. Choose one to open, or add another — up to three on one device.",
  "vaults.open": "Open vault {fp}",
  "vaults.created": "Created {date}",
  "vaults.current": "Last opened",
  "vaults.create": "Create a new vault",
  "vaults.import": "Import a vault from a backup file",
  "vaults.limit": "Up to {n} vaults on this device",
  "vaults.full": "This device holds {n} vaults, which is the limit. Remove one from its Settings before adding another.",
  "vaults.n": "{n} vaults",
  "vaults.n.one": "one vault",
  "vaults.back": "Back to your vaults",
  "genesis.warn.restarted": "Setup started over. The app left the foreground, so the 24 words were wiped from memory rather than left sitting behind the task switcher. Nothing was created and nothing was saved. What you had already marked is still marked.",

  // ---- genesis C2 passphrase
  "pass.step": "Step 1 of 4",
  "pass.title": "A passphrase, or not",
  "pass.body": "A passphrase is a second secret, kept apart from the 24 words. Both are needed to open the vault — neither one alone does anything.",
  "pass.split": "This lets you split the secret between two people. Give your sister the words on metal and your lawyer the passphrase on paper, and neither can read your messages alone. It also means that if one of them loses their half, no one ever reads them. Choose it deliberately.",
  "pass.off.t": "No passphrase",
  "pass.off.b": "The 24 words alone open the vault. Simplest to leave behind; one secret to protect.",
  "pass.gen.t": "Let the app choose five words",
  "pass.gen.b": "Drawn from the same wordlist, at random. Easier to transcribe by hand than a password, and impossible to guess.",
  "pass.gen.redraw": "Draw five more",
  "pass.gen.note": "You will be asked to type these back before the vault is created. There is no copy button here, and there will not be one later.",
  "pass.own.t": "My own passphrase",
  "pass.own.b": "At least 12 characters. A phrase you have never typed anywhere else.",
  "pass.own.short": "Too short — at least 12 characters.",
  "pass.own.weak": "Weak. Longer is better than stranger.",
  "pass.own.ok": "Strong enough. Longer is better than stranger.",
  "pass.nfkd": "Spaces, capital letters and accents all matter, exactly as typed. The text is normalised (NFKD) but not otherwise changed — “Bangkok 2019” and “bangkok 2019” are different secrets.",
  "pass.thai": "For Thai: the order you type vowel signs and tone marks changes the passphrase, even when the letters look identical.",
  "pass.locked": "This choice cannot be changed later without re-keying the whole vault.",

  // ---- genesis C3 phrase
  "phrase.step": "Step 2 of 4",
  "phrase.title": "Write these down",
  "phrase.sub": "Four at a time, in this order. The numbers are part of the phrase — a right word in a wrong place opens nothing.",
  "phrase.screenshot": "Do not photograph this screen. Write the words by hand, or punch them into metal.",
  "phrase.range": "Words {from}–{to} of {total}",
  "phrase.shownumber": "Show the word number too",
  "phrase.shownumber.b": "For punching a TinySeed plate. Counts from 1.",
  "phrase.next": "Next four",
  "phrase.last": "I have written all 24 down",
  "phrase.print": "Print a plate template instead",
  "phrase.english": "The 24 words are always English, even when the app is in Thai, because you copy them by hand and type them back letter by letter.",

  // ---- genesis C6 derive
  "derive.step": "Step 3 of 4",
  "derive.title": "Working out your key",
  "derive.why": "This is slow on purpose. The same slowness is what stops someone guessing your phrase by brute force. Keep the screen on.",
  "derive.failed": "That did not finish. Nothing has been changed — try again.",
  "derive.body": "This takes between three and ten seconds, and it will take that long every time you open the vault. The wait is the protection: it is what makes trying millions of guesses impractical for anyone who finds this phone.",
  "derive.keepawake": "Keep the screen awake and stay in the app. If you switch away, the screen blanks and this starts again from the beginning.",
  "derive.where": "Argon2id, run in plain JavaScript on this device. Nothing is sent anywhere — the phone is doing all of this by itself, which is also why it is slow.",
  "derive.s1": "Phrase checked against the wordlist",
  "derive.s2": "Deriving the vault key",
  "derive.s3": "Self-test: seal and open a sample",
  "derive.elapsed": "{n}s",
  "derive.unknown": "No progress figure from this step — the elapsed time is the only honest measure.",
  "derive.opening": "Opening",
  "derive.opening.body": "Between three and ten seconds. The app does not yet know whether your phrase is right — it has to do all of this work first, and that is exactly what makes guessing impractical.",
  "derive.opening.keepon": "Keep the screen on. Switching apps blanks the screen and cancels this.",
  "derive.opening.state": "24 words · {pass}",
  "derive.opening.passset": "passphrase set",
  "derive.opening.passnone": "no passphrase",
  "derive.opening.gone": "Your words are already out of the fields and out of the screen. They exist only inside this calculation, and they are gone the moment it ends, whether it succeeds or not.",
  "derive.cancel": "Cancel",
  "derive.bench": "Measuring how fast this device is, so the vault can be as slow as it safely can be.",

  // ---- genesis C5 verify
  "verify.step": "Step 4 of 4",
  "verify.title": "Prove you wrote them down",
  "verify.body": "All twenty-four, in order, plus your passphrase. This is the same screen you will see whenever you open the vault — it is worth getting used to now.",
  "verify.count": "{n} of {total} words in place",
  "verify.pending": "checksum pending",
  "verify.checksumnote": "The last word carries a checksum. Until all twenty-four are entered, the app cannot tell you whether the phrase is right — only whether each word exists.",
  "verify.submit": "Check and create the vault",
  "verify.showagain": "Show me the words again",
  "verify.mismatch": "Those are not the words this app just gave you. Go back, read them again, and re-enter them.",

  // ---- genesis C7 done
  "done.title": "Your vault exists",
  "done.body": "It lives on this phone and nowhere else. The words you wrote down are the only way back into it, and the app has already forgotten them.",
  "done.fp": "Vault fingerprint",
  "done.fp.note": "Write this next to your words. It tells you later whether a backup file and a phrase belong to the same vault. It reveals nothing on its own.",
  "done.left.t": "One thing left",
  "done.left.b": "Save a backup file somewhere else — another device, a drive, a cloud folder. The file holds only encrypted data and is useless without your phrase, so it is safe to keep almost anywhere.",
  "done.backup": "Save a backup now",
  "done.print": "Print the plate template",
  "done.print.note": "Requires the phrase you have just verified — it is still in memory for a few more seconds.",
  "done.skip": "Skip for now",
  "done.skip.note": "Skipping leaves a red “never backed up” banner on the home screen until you do it. The banner has no dismiss button.",

  // ---- home
  "home.persisted": "Storage held",
  "home.notpersisted": "Storage not guaranteed",
  "home.persist.ask": "Ask again for persistent storage",
  "home.persist.body": "This phone has not promised to keep the vault. If storage runs low, the system may clear it without asking. Adding the app to your home screen usually fixes this.",
  "home.count": "{n} sealed messages",
  "home.count.one": "One sealed message",
  "home.nothing.t": "Nothing sealed yet",
  "home.nothing.b": "When you write something it appears here as a numbered line with no words in it. That is not a bug — the app genuinely cannot read what you have written until the phrase is entered.",
  "home.nopreview": "Nothing on this screen can be read, including by you. What is here is a count, an order and a rough size — enough to know the vault is intact, and nothing more.",
  "home.entry.meta": "Sealed · about {size} · {date}",
  "home.entry.bad": "Does not match its seal · about {size} · {date}",
  "home.write": "Write",
  "home.unlock": "Unlock to read",
  "home.backup": "Back up",
  "home.restore": "Restore",
  "home.settings": "Settings",
  "home.vaults": "Switch vault",
  "home.emptydisabled": "Unlock and Back up stay disabled while the vault is empty — there is nothing to open or save.",
  "home.backup.never": "Never backed up",
  "home.backup.never.s": "This vault exists in exactly one place.",
  "home.backup.days": "Backed up {n} days ago",
  "home.backup.today": "Backed up today",
  "home.backup.fine": "Nothing to do.",
  "home.backup.stale": "Newer messages exist only on this phone.",
  "home.backup.urgent": "If this phone is lost today, most of the vault is lost with it.",
  "home.backup.one": "One message exists only on this phone.",
  "home.backup.some": "{n} messages exist only on this phone.",

  // ---- write
  "write.title": "New message",
  "write.seal": "Seal",
  "write.for": "Intended for",
  "write.for.optional": "— optional",
  "write.for.note": "Sealed together with the message, so this label is unreadable until the vault is opened. It is a note to whoever gets in, not a way to send anything.",
  "write.chars": "{n} characters",
  "write.storedsize": "Stored size",
  "write.padnote": "Everything is padded out to one of three sizes so that the length of what you wrote gives nothing away. Writing does not ask for your phrase — the vault can always be added to, only never read, without it.",
  "write.toolong": "Too long for the largest size. Shorten it, or split it into two messages.",
  "write.empty": "Write something first.",
  "write.sealed.title": "Sealed",
  "write.sealed.body": "Only the phrase can open this. It is entry {n} in your vault, and from here on neither this app nor you can see what it says without entering all twenty-four words.",
  "write.sealed.stale": "Your last backup is from {n} days ago and does not contain this message. Save a new one before you put the phone down.",
  "write.sealed.never": "There is no backup of this vault yet. Save one before you put the phone down.",
  "write.backupnow": "Back up now",
  "write.another": "Write another",
  "write.thaicount": "One Thai character takes more room than an English one in UTF-8, so the counter counts visible characters while the stored size counts real bytes.",

  // ---- unlock
  "unlock.title": "Open the vault",
  "unlock.body": "Enter all twenty-four words in order, then the passphrase. Nothing is checked until the last word is in place.",
  "unlock.mode.type": "Type words",
  "unlock.mode.grid": "Plate grid",
  "unlock.mode.numbers": "Numbers",
  "unlock.passphrase": "Passphrase",
  "unlock.passphrase.note": "Spaces and capitals matter. This is not your phone’s password field — nothing offers to save it, and nothing will.",
  "unlock.nomask": "This browser cannot hide the passphrase without using a password field, and a password field would offer to remember it. The text stays visible here — shield the screen instead.",
  "unlock.reveal": "Show passphrase",
  "unlock.hide": "Hide passphrase",
  "unlock.submit": "Open — {n} of 24 words",
  "unlock.submit.ready": "Open the vault",
  "unlock.leave": "Opening takes three to ten seconds. Leaving this screen clears everything you have typed.",
  "unlock.notaword": "Not a BIP39 word",
  "unlock.suggestion": "Word {n} — suggestion",
  "unlock.paste.warn": "Pasted across all 24 fields. A phrase that has been on a clipboard is no longer private — treat it as exposed and move the vault when you can.",
  "unlock.numbering": "Which numbering is on your plate?",
  "unlock.numbering.note": "Get this wrong and every word shifts by one. Check a plate you can already read before trusting it.",
  "unlock.numbering.tiny": "TinySeed",
  "unlock.numbering.tiny.s": "starts at 1",
  "unlock.numbering.bip39": "BIP39 index",
  "unlock.numbering.bip39.s": "starts at 0",
  "unlock.numbering.current": "Numbering",
  "unlock.numbering.change": "Change",
  "unlock.grid.note": "The row you are working on stays under your thumb while the list scrolls, and each row’s resolved word appears the moment its punches add up to a number in range.",
  "unlock.grid.arabic": "Weights and word numbers are always Arabic digits, never Thai numerals, because they must match the metal plate in your hand.",
  "unlock.grid.notset": "not set",
  "unlock.grid.outofrange": "out of range",
  "unlock.grid.rowbad": "Row {n} is out of range. {sum} is higher than 2048, so it cannot be a word. Check whether that punch in the 1024 column was meant for the 16 column.",
  "unlock.grid.clear": "Clear row {n}",
  "unlock.submit.outofrange": "Open — one number out of range",

  "unlock.err.checksum.t": "These 24 words are not a valid phrase",
  "unlock.err.checksum.b": "The last word of a BIP39 phrase checks the other twenty-three. That check failed, which means at least one word is wrong or out of order — not that the vault is damaged.",
  "unlock.err.checksum.suspects": "Worth checking first",
  "unlock.err.checksum.why.last": "The last word carries the checksum, so an error anywhere shows up here",
  "unlock.err.checksum.why.near": "This word differs from its neighbours in the list by one bit — easy to misread on a plate",
  "unlock.err.checksum.note": "These positions are the ones most likely to be at fault. The app cannot tell you the right words — it does not know them. If they all look correct, the error is probably an order swap between two neighbouring rows.",
  "unlock.err.noattempts": "No attempt has been counted and nothing is locked out. You can try as often as you like — the three to ten seconds is the only limit there is.",
  "unlock.err.back": "Go back to my words",
  "unlock.err.cannotget": "What if I cannot get in?",

  "unlock.err.pass.t": "The words are right. The passphrase is not.",
  "unlock.err.pass.b": "All twenty-four words form a valid phrase, and the key that came out of them does not open this vault. With a passphrase set, that almost always means the passphrase is wrong.",
  "unlock.err.pass.things": "Things that change a passphrase",
  "unlock.err.pass.t1": "A capital letter at the start that a keyboard added by itself",
  "unlock.err.pass.t2": "A trailing space, often left by paste or autocorrect",
  "unlock.err.pass.t3": "Straight quotes turned into curly ones",
  "unlock.err.pass.t4": "A Thai keyboard layout producing visually identical vowel signs in a different order",
  "unlock.err.pass.t5": "The five generated words separated by two spaces instead of one",
  "unlock.err.pass.empty": "If you never set a passphrase on this vault, leave the field completely empty rather than typing a space. An empty field and a single space are different secrets.",
  "unlock.err.pass.kept": "Your words are still entered. Only the passphrase field has been cleared, so you do not have to start over.",
  "unlock.err.pass.retry": "Try the passphrase again",
  "unlock.err.pass.stop": "Stop for now",

  "unlock.err.other.t": "This phrase belongs to a different vault",
  "unlock.err.other.b": "The phrase is valid and the key it produced is a real vault key — just not this one. Nothing is wrong with either. You are most likely holding the phrase for another vault you made.",
  "unlock.err.other.here": "This device holds",
  "unlock.err.other.yours": "Your phrase opens",
  "unlock.err.other.note": "Fingerprints are derived from the key, not from your words. Showing you this one gives nothing away and is the fastest way to tell two vaults apart.",
  "unlock.err.other.restore": "Restore that vault from a file",
  "unlock.err.other.retry": "Try a different phrase",

  // ---- read
  "read.title": "Open",
  "read.sub": "{n} messages, newest first. Nothing here leaves this screen.",
  "read.sub.one": "One message. Nothing here leaves this screen.",
  "read.relock": "Locks again in {time}",
  "read.locknow": "Lock now",
  "read.extend": "Snooze — two more minutes",
  "read.nolabel": "No label",
  "read.when": "{date} · entry {n}",
  "read.tapread": "Tap to read — {size}, longer than the others.",
  "read.damaged": "This entry does not match its seal and cannot be opened.",
  "read.delete": "Delete this entry",
  "read.norelease": "Nothing here can be copied out, shared or exported as readable text. When the timer runs out the screen returns to the locked list and the key is discarded — getting back in means the phrase again.",
  "read.sr.relock": "Vault locks again in {n} seconds.",
  "read.keys": "↑↓ move · Enter open · Esc lock",

  // ---- blank
  "blank.t": "Hidden while the app is in the background.",
  "blank.b": "Tap to return. Anything that was open has been locked.",

  // ---- backup / restore
  "backup.title": "Back up",
  "backup.headline": "One file, still sealed",
  "backup.body": "The file holds your messages exactly as they are stored here: encrypted. It contains no phrase, no passphrase and no key. Someone who finds it learns how many messages you have written and roughly how long they are — nothing else.",
  "backup.filemeta": "{size} · {n} messages · sealed",
  "backup.filemeta.one": "{size} · one message · sealed",
  "backup.fpname": "The fingerprint is in the filename so that later you can tell which vault a file belongs to without opening anything.",
  "backup.where": "Keep it somewhere ordinary and durable: a cloud drive, an email to yourself, a USB stick in a drawer. Storing it next to your written-down phrase defeats the point — keep the two apart.",
  "backup.share": "Share the file",
  "backup.download": "Download",
  "backup.sharenote": "Opens your phone’s share sheet. On a desktop this button reads Download instead.",
  "backup.saved": "Saved. The backup banner is reset from today.",
  "backup.failed": "The file was not saved. Nothing has changed — try again.",

  "restore.title": "Restore",
  "restore.choose": "Choose a backup file",
  "restore.nophrase": "Restoring never asks for your phrase. The file stays sealed — the app only checks that it is a real backup and which vault it belongs to.",
  "restore.pick": "Choose a file",
  "restore.pick.s": ".dmv files, from this phone or a cloud drive",
  "restore.checks": "Checked before anything changes",
  "restore.c1": "The file is a Dying Message backup and not something else",
  "restore.c2": "Its internal structure is complete and not truncated",
  "restore.c3": "Which vault fingerprint it belongs to",
  "restore.c4": "How many of its entries this device does not already have",
  "restore.safe": "Nothing already on this phone is deleted or overwritten by a restore. In the worst case you end up with entries you did not want, which you can delete afterwards.",
  "restore.multidevice": "Using the same phrase on a second device and restoring its backup here is how one vault lives in two places.",
  "restore.new.t": "This vault is not on this device yet",
  "restore.new.b": "The file becomes a vault on this device, exactly as it was when the backup was made. You will need its 24 words to read anything — restoring gives you the sealed messages, not the key.",
  "restore.new.meta": "{fp} · {n} entries",
  "restore.new.go": "Restore this vault",
  "restore.same.t": "Same vault — {n} messages will be added",
  "restore.same.t.one": "Same vault — one message will be added",
  "restore.same.t.none": "Same vault — nothing new in this file",
  "restore.same.b": "This file belongs to the vault already on this device. {new} of its entries are not here yet; the other {old} already are and will be left alone. Nothing on this device is replaced.",
  "restore.same.new": "New — will be added",
  "restore.same.old": "Already here — left alone",
  "restore.same.go": "Add the new messages",
  "restore.bad": "This is not a Dying Message backup, or it has been truncated. Nothing has been changed.",
  "restore.added": "{n} messages added.",
  "restore.added.one": "One message added.",
  "restore.full.t": "No room for another vault",
  "restore.full.b": "This file is a vault that is not on this device, and the device already holds {n} — the limit. Remove one from its Settings first, then restore this file.",

  // ---- settings
  "set.title": "Settings",
  "set.app": "This app",
  "set.relock": "Lock again after",
  "set.relock.s": "While a message is open on screen",
  "set.relock.1": "1 minute",
  "set.relock.2": "2 minutes",
  "set.relock.5": "5 minutes",
  "set.relock.manual": "Until I lock it",
  "set.relock.manual.note": "The vault stays open until you press Lock or leave the app. If you put the phone down with it open, it is open.",
  "set.language": "Language",
  "set.language.s": "Changes every word in the app",
  "set.theme": "Theme",
  "set.theme.s": "Follows the system unless set",
  "set.theme.auto": "Automatic",
  "set.theme.light": "Light",
  "set.theme.dark": "Dark",
  "set.vault": "This vault",
  "set.fp": "Fingerprint",
  "set.name": "Nickname",
  "set.name.s": "A label for this vault on the picker and the list. It stays on this device and is never written into a backup file — a backup should not say what it is for.",
  "set.print": "Print the TinySeed grid",
  "set.print.s": "Needs your phrase — the app does not have it",
  "set.rekey": "Change the passphrase",
  "set.rekey.s": "Needs your phrase and a backup made today",
  "set.rekey.b": "Changing the passphrase re-seals every message under a new key. If it is interrupted halfway, the backup is what saves you — which is why the app insists on a fresh one first.",
  "set.rekey.needbackup": "Back up first. The button unlocks once today’s backup exists.",
  "set.rekey.new": "New passphrase",
  "set.rekey.confirm": "Type the new passphrase again",
  "set.rekey.nomatch": "The two do not match.",
  "set.rekey.go": "Re-seal every message",
  "set.rekey.done": "Done. Every message is now sealed under the new passphrase, and the fingerprint has changed to {fp}. Back up again now — your old backup file needs the old passphrase.",
  "diag.title": "Diagnostics",
  "diag.body": "Everything that decides whether this app can be installed, and whether what you write here will survive. Red means it is a problem.",
  "diag.share": "Nothing on this screen is secret — no message, phrase or passphrase appears here. Photograph it if you need help.",
  "diag.open": "Diagnostics",
  "set.version": "Version",
  "set.version.app": "App version",
  "set.version.hash": "Release hash",
  "set.checkupdate": "Check for an update",
  "set.remove": "Remove this vault from this device",
  "set.remove.b": "Everything in this vault is erased; other vaults on this device are untouched. A backup file elsewhere, plus your phrase, is the only way back. You will be asked to type the fingerprint to confirm.",
  "set.irreversible": "Irreversible",

  // ---- destructive confirmation
  "confirm.type": "Type {phrase} to confirm",
  "confirm.delete.entry.t": "Delete entry {n}",
  "confirm.delete.entry.b": "This entry is removed from this device. If it is in a backup file you have kept, that copy survives; if it is not, it is gone and cannot be brought back.",
  "confirm.delete.entry.go": "Delete permanently",
  "confirm.delete.entry.phrase": "delete entry {n}",
  "confirm.remove.vault.t": "Remove this vault",
  "confirm.remove.vault.b": "Every sealed message in this vault is erased, along with the vault’s public keys. A backup file plus your 24 words is the only way to see any of it again.",
  "confirm.remove.vault.go": "Erase this vault",

  // ---- print
  "print.title": "Recovery phrase — plate template",
  "print.sub": "Dying Message · BIP39 24 words · TinySeed bit layout",
  "print.vault": "Vault",
  "print.date": "Date",
  "print.how": "Punch the marked squares on each row. The marked weights add up to the number in the last column, which is the word’s position in the BIP39 list counting from 1. Row order matters as much as the words.",
  "print.burn": "Burn or shred this sheet once the plate is punched. Paper in a drawer is the most common way a phrase is lost — and the most common way one is found by the wrong person.",
  "print.nopass": "This sheet does not contain the passphrase, if you set one. That is a separate secret and must be kept somewhere else.",
  "print.word": "Word",
  "print.sum": "Sum",
  "print.legend": "Filled square = punch. Empty square = leave.",
  "print.foot": "Page {n} of {total} · prints in black and white · no colour is load-bearing",
  "print.notes.title": "How to use this sheet",
  "print.badword": "This sheet was not printed. Word {n} is not in the BIP39 list, so the app cannot work out its number, and a sheet with a blank row would be punched wrong. Go back and check the phrase.",
  "print.preview": "This is the sheet exactly as it will print. Check the words against the screen before you punch anything.",
  "print.go": "Print this sheet",
  "print.blocked": "Printing is turned off on this screen, because the page would carry something that should not be on paper. The plate template is the one page this app prints.",

  // ---- guide
  "guide.title": "Guide",
  "guide.what.t": "What this app is",
  "guide.what.b1": "It is a place to write things you want read after you are gone, and to make sure nobody reads them before then.",
  "guide.what.b2": "When the app was set up it produced twenty-four ordinary English words in a fixed order. Those words are the key. Everything written here is locked with them and cannot be unlocked by anything else. The words are not stored in the app, or on any server — there are no servers. They exist only wherever they were written down.",
  "guide.what.b3": "So the app can be opened, looked through and even copied, and it gives nothing away. Whoever holds the words holds everything.",
  "guide.cannot.t": "What it cannot do",
  "guide.cannot.b": "It cannot help you if the words are lost. This is the part people do not believe until it happens, so it is worth saying plainly: there is no reset link, no support address, no back door, and no clever technique. A lost phrase means the messages stay locked for ever.",
  "guide.cannot.1": "It cannot recover a lost phrase, or any part of one.",
  "guide.cannot.2": "It cannot tell you what the words were, or how many you have wrong.",
  "guide.cannot.3": "It cannot send a message to anyone, now or later. Someone has to be given the words.",
  "guide.cannot.4": "It cannot know you have died. Nothing here is triggered by anything.",
  "guide.cannot.5": "It cannot survive the app being deleted from the device unless a backup file exists elsewhere.",
  "guide.keep.t": "Keeping the twenty-four words",
  "guide.keep.b": "Two things can go wrong: the words are destroyed, or they are found by the wrong person. Guard against both, and remember that most losses are dull — a flood, a house move, a helpful relative clearing out a drawer.",
  "guide.keep.1.t": "Write them by hand, on paper, twice",
  "guide.keep.1.b": "Two copies in two buildings. Paper is unfashionable and it has outlasted every storage format invented since.",
  "guide.keep.2.t": "Better: punch them into a metal plate",
  "guide.keep.2.b": "The app prints a template for this. Metal survives fire and water; paper does not, and neither does a hard drive.",
  "guide.keep.3.t": "Keep the order and the numbers",
  "guide.keep.3.b": "A right word in the wrong position is a wrong word. Number every line 1 to 24.",
  "guide.keep.4.t": "Tell someone it exists",
  "guide.keep.4.b": "The most common failure is not theft. It is that nobody knew the drawer mattered, and it was cleared out with everything else.",
  "guide.keep.never": "Do not photograph the words, type them into a notes app, or email them to yourself. Anything on a phone or a computer is backed up somewhere you have forgotten about, and read by something you did not agree to.",
  "guide.split.t": "Splitting it between two people",
  "guide.split.b1": "If a passphrase was set, there are two secrets rather than one, and both are needed. That lets you give the twenty-four words to one person and the passphrase to another.",
  "guide.split.b2": "Neither of them can read anything alone. Together, they can. It is a way of saying “these two should agree before this is opened” without relying on anyone’s goodwill.",
  "guide.split.b3": "The cost is real. If either half is lost, the messages are lost, and you have doubled the number of ways that can happen. Tell both people that the other exists, and write down — somewhere ordinary, with your will — that two halves are needed and who has them. The halves stay secret; the arrangement should not.",
  "guide.multi.t": "Using more than one device",
  "guide.multi.b": "There is no syncing, because syncing would need a server. Instead, the same phrase can be entered on a second device, and a backup file carried over to it.",
  "guide.multi.1": "Install the app on the second device and enter the same twenty-four words and passphrase.",
  "guide.multi.2": "Make a backup file on the first device, and move it across however you like — the file is encrypted, so email or a cloud drive is fine.",
  "guide.multi.3": "Restore that file on the second device. It will say how many messages it is adding.",
  "guide.multi.after": "Both devices then hold the same vault. Writing on one does not appear on the other until you carry another backup across — so it is worth deciding which device is the one you actually write on.",
  "guide.heirs.t": "If someone has left you these words",
  "guide.heirs.b": "Someone wrote you something and arranged for you to be able to read it. There is no hurry — the messages will keep, and nothing expires. Read this part when you are ready.",
  "guide.heirs.1.t": "Find the app",
  "guide.heirs.1.b": "It is an icon on a phone, tablet or computer, called Dying Message. It will not work from a web address alone — it must be the installed icon, on the device where the messages were written, or on a device where a backup file has been restored.",
  "guide.heirs.2.t": "Press “Unlock to read”",
  "guide.heirs.2.b": "Then type the twenty-four words in the order they were given to you. If you were given a metal plate rather than words, choose “Plate grid” and tap the marked squares row by row.",
  "guide.heirs.3.t": "If you were given a passphrase too",
  "guide.heirs.3.b": "Type it exactly as written, including capital letters and spaces. It goes in the field below the words.",
  "guide.heirs.4.t": "If you were given a file",
  "guide.heirs.4.b": "Install the app on any device, choose “Restore”, and pick the file. Then unlock it with the words as above.",
  "guide.heirs.5.t": "Nothing you do can break it",
  "guide.heirs.5.b": "Wrong words are simply refused. You cannot damage or erase the messages by trying.",
  "guide.heirs.wait": "The three to ten second wait when you press Open is normal, and it happens every time. Nothing has frozen.",
  "guide.stuck.t": "If it will not open",
  "guide.stuck.b": "Work through this in order. There is no limit on attempts and nothing locks you out, so take as long as you need.",
  "guide.stuck.1": "Check the order. Read your list from 1 to 24 and compare it with the numbers on screen.",
  "guide.stuck.2": "Check for a misread letter. Handwritten “rn” looks like “m”; “l” and “1” trade places. The app only accepts real words from its list, so a wrong letter usually shows up straight away.",
  "guide.stuck.3": "If you have a plate, check which numbering it uses. Some plates count from 1, some from 0. The app has a switch for this, and getting it wrong shifts every word.",
  "guide.stuck.4": "Check the passphrase for a stray space at the end, or a capital letter the keyboard added by itself.",
  "guide.stuck.5": "If the app says the phrase belongs to a different vault, the words are valid — they just open something else. Look for another backup file, or another device.",
  "guide.foot": "This app was built to be boring and to outlast whoever made it. It sends nothing, asks for nothing, and will keep working with no internet connection for as long as the device it is installed on keeps working.",

  // ---- screen-reader labels
  "sr.gridcell": "word {w}, bit {bit}, {state}",
  "sr.punched": "punched",
  "sr.notpunched": "not punched",
  "sr.rowresolves": "word {w} resolves to {word}, {idx}",
  "sr.rowunset": "word {w}, no punches yet",
  "sr.wordfield": "word {n} of 24",
  "sr.inwordlist": "In the wordlist.",
  "sr.notinwordlist": "Not in the wordlist.",
  "sr.entry": "entry {n}, sealed, about {size}, {date}",
  "sr.entrybad": "entry {n}, does not match its seal, about {size}, {date}",
  "sr.derive": "Working out the key. This takes three to ten seconds and is slow on purpose. {n} seconds elapsed.",
};

export const th = {
  "common.back": "ย้อนกลับ",
  "common.cancel": "ยกเลิก",
  "common.continue": "ไปต่อ",
  "common.done": "เสร็จสิ้น",
  "common.close": "ปิด",
  "common.keepit": "เก็บไว้",
  "common.checkagain": "ตรวจสอบอีกครั้ง",
  "common.guide": "อ่านคู่มือ",

  "install.strip": "อย่าตั้งค่าที่เก็บในเบราว์เซอร์ ข้อมูลที่คุณสร้างในแท็บนี้จะอยู่แค่ในแท็บ และจะไม่ถูกย้ายไปยังแอปที่ติดตั้ง",
  "install.title": "แอปนี้ต้องติดตั้งก่อนใช้งาน",
  "install.noicons.t": "แอปชุดนี้ไม่สมบูรณ์",
  "install.noicons.b": "ไอคอนของแอปหายไปจากเซิร์ฟเวอร์ และเบราว์เซอร์จะไม่เสนอให้ติดตั้งเว็บที่โหลดไอคอนไม่ได้ หากเพิ่มไปยังหน้าจอหลักตอนนี้ จะได้เพียงทางลัดบุ๊กมาร์ก ไม่ใช่แอปที่ติดตั้งจริง และที่เก็บที่สร้างในทางลัดอาจถูกลบได้โดยไม่มีการเตือน ผู้ที่เผยแพร่แอปนี้ต้องอัปโหลดโฟลเดอร์ไอคอนขึ้นไปด้วย",
  "install.insecure.t": "หน้านี้ไม่ได้ถูกส่งมาอย่างปลอดภัย",
  "install.insecure.b": "ที่อยู่เว็บต้องขึ้นต้นด้วย https และมีใบรับรองที่ถูกต้อง หากเป็น http ธรรมดา เบราว์เซอร์จะไม่ติดตั้งแอป ไม่รัน service worker และไม่รักษาพื้นที่จัดเก็บไว้ให้ จึงไม่มีที่ใดที่ปลอดภัยพอจะเก็บที่เก็บได้ ผู้ที่เผยแพร่แอปนี้ต้องเปิดใช้ HTTPS บนโดเมน",
  "install.swfailed.t": "แอปเริ่ม service worker ไม่สำเร็จ",
  "install.swfailed.b": "เบราว์เซอร์จะไม่ติดตั้งเว็บที่ service worker ลงทะเบียนไม่สำเร็จ และหากไม่มี แอปจะทำงานออฟไลน์ไม่ได้ เหตุผลที่เบราว์เซอร์แจ้งไว้อยู่ด้านล่าง",
  "install.waiting": "เบราว์เซอร์นี้ยังไม่ได้เสนอให้ติดตั้งแอป มักเป็นเพราะหน้าเว็บยังโหลดไม่เสร็จ หรือมีบางอย่างที่จำเป็นหายไปจากเซิร์ฟเวอร์ ขั้นตอนด้วยมือด้านล่างยังใช้ได้หากการติดตั้งพร้อมใช้งานจริง",
  "install.already.t": "ติดตั้งไว้แล้วใช่ไหม",

  "lang.title": "ภาษา",
  "lang.body": "เครื่องนี้ตั้งค่าเป็นภาษาไทย แอปจึงใช้ภาษาไทยด้วย กรุณายืนยันก่อนไปต่อ เพราะสิ่งที่อยู่ถัดจากนี้เปลี่ยนแปลงไม่ได้ และควรอ่านในภาษาที่คุณอ่านได้ดีที่สุด",
  "lang.th": "ไทย",
  "lang.en": "English",
  "lang.wordsnote": "คำทั้ง 24 คำเป็นภาษาอังกฤษเสมอ ไม่ว่าจะเลือกภาษาใด เพราะต้องคัดลอกด้วยมือและพิมพ์กลับทีละตัวอักษร",
  "lang.changeable": "เปลี่ยนได้ทุกเมื่อในหน้าตั้งค่า",
  "lang.follow": "ตามการตั้งค่าของเครื่อง",
  "lang.inuse": "กำลังใช้งานอยู่",
  "lang.whatchanges": "สิ่งที่เปลี่ยน",
  "lang.ch1": "ทุกป้ายกำกับ หัวข้อ คำเตือน และข้อความแจ้งข้อผิดพลาดในแอป",
  "lang.ch2": "คู่มือ ขั้นตอนการติดตั้ง และคำอธิบายบนแผ่นที่พิมพ์ออกมา",
  "lang.ch3": "รูปแบบวันที่ — 2 มีนาคม 2569 ในภาษาไทย และ 2 March 2026 ในภาษาอังกฤษ",
  "lang.ch4": "คำทั้ง 24 คำ — เป็นภาษาอังกฤษเสมอ",
  "lang.ch5": "ข้อความของคุณเอง — จัดเก็บตามที่คุณพิมพ์ทุกประการ",
  "lang.ch6": "ลายนิ้วมือของที่เก็บ ค่าแฮชของรุ่น และชื่อไฟล์สำรอง",
  "lang.immediate": "การเปลี่ยนภาษามีผลทันทีและไม่กระทบสิ่งที่จัดเก็บไว้ ที่เก็บ ข้อความข้างใน และชุดคำที่ใช้เปิดเหมือนเดิมทั้งสองภาษา ที่เก็บที่สร้างเป็นภาษาไทยเปิดได้บนเครื่องภาษาอังกฤษ และในทางกลับกันด้วย",
  "lang.heirs": "คนที่ได้รับชุดคำของคุณอาจอ่านภาษาที่คุณเลือกไม่ออก ควรระบุไว้ด้วยว่าแอปตั้งเป็นภาษาอะไร เมื่อคุณส่งมอบชุดคำ",

  "genesis.warn.title": "ก่อนเริ่มต้น",
  "genesis.warn.sub": "ห้าข้อต่อไปนี้เปลี่ยนแปลงไม่ได้ กรุณาอ่านและกดยืนยันทีละข้อ",
  "genesis.w1.t": "ไม่มีทางกู้คืนได้",
  "genesis.w1.b": "หากทำคำทั้ง 24 คำหาย ข้อความทุกข้อความในที่เก็บนี้จะอ่านไม่ได้อีกตลอดไป ไม่มีการรีเซ็ต ไม่มีอีเมลติดต่อ และไม่มีสำเนาเก็บไว้ที่ใดทั้งสิ้น",
  "genesis.w2.t": "แอปนี้ห้ามการถ่ายภาพหน้าจอไม่ได้",
  "genesis.w2.b": "โทรศัพท์ของคุณถ่ายภาพคำในหน้าถัดไปได้ ภาพนั้นจะไปอยู่ในคลังรูปภาพ และมักถูกสำรองขึ้นคลาวด์ต่อไปอีกทอดหนึ่งโดยที่คุณไม่รู้ตัว",
  "genesis.w3.t": "ลบไอคอนออก คือลบที่เก็บทิ้ง",
  "genesis.w3.b": "ข้อความอยู่ในแอปที่ติดตั้งไว้ การลบแอปออกจากหน้าจอหลักคือการลบข้อความไปพร้อมกัน ให้เก็บไฟล์สำรองไว้ที่อื่นเสมอ",
  "genesis.w4.t": "อย่าใช้ชุดคำเดิมกับกระเป๋าคริปโท",
  "genesis.w4.b": "ถ้าคำชุดนี้ใช้ดูแลเงินอยู่ด้วย คนที่ควรได้อ่านข้อความของคุณจะใช้เงินนั้นได้ ให้แอปสร้างชุดคำใหม่ให้",
  "genesis.w5.t": "ช้าโดยตั้งใจ",
  "genesis.w5.b": "การเปิดที่เก็บใช้เวลาหลายวินาทีทุกครั้ง ความช้านี้คือสิ่งที่ทำให้การไล่เดาคำเป็นไปไม่ได้จริงในทางปฏิบัติ",
  "genesis.warn.count": "ยืนยันแล้ว {n} จาก {total}",
  "genesis.warn.create": "สร้างที่เก็บของฉัน",
  "genesis.warn.guidefirst": "อ่านคู่มือฉบับเต็มก่อน",
  "genesis.warn.import": "กู้คืนที่เก็บจากไฟล์สำรอง",
  "vaults.title": "ที่เก็บของคุณ",
  "vaults.body": "ที่เก็บแต่ละแห่งมีคำ 24 คำและข้อความที่ปิดผนึกเป็นของตัวเอง เลือกที่เก็บที่จะเปิด หรือเพิ่มอีกแห่ง ได้สูงสุดสามแห่งต่อเครื่อง",
  "vaults.open": "เปิดที่เก็บ {fp}",
  "vaults.created": "สร้างเมื่อ {date}",
  "vaults.current": "เปิดล่าสุด",
  "vaults.create": "สร้างที่เก็บใหม่",
  "vaults.import": "นำเข้าที่เก็บจากไฟล์สำรอง",
  "vaults.limit": "เครื่องนี้มีที่เก็บได้สูงสุด {n} แห่ง",
  "vaults.full": "เครื่องนี้มีที่เก็บอยู่ {n} แห่งแล้ว ซึ่งเป็นจำนวนสูงสุด ให้ลบที่เก็บแห่งหนึ่งออกจากหน้าตั้งค่าของมันก่อน จึงจะเพิ่มได้อีก",
  "vaults.n": "{n} แห่ง",
  "vaults.n.one": "1 แห่ง",
  "vaults.back": "กลับไปหน้าที่เก็บของคุณ",
  "genesis.warn.restarted": "การตั้งค่าเริ่มใหม่ เนื่องจากแอปออกจากหน้าจอ คำทั้ง 24 คำจึงถูกลบออกจากหน่วยความจำ แทนที่จะค้างไว้หลังหน้าสลับแอป ไม่มีสิ่งใดถูกสร้างหรือถูกบันทึก ข้อที่คุณยืนยันไว้แล้วยังคงอยู่",

  "pass.title": "วลีรหัสผ่าน หรือไม่ใช้",
  "pass.thai": "หากใช้ภาษาไทยเป็นวลีรหัสผ่าน ลำดับการพิมพ์สระและวรรณยุกต์มีผลต่อรหัสผ่าน แม้ตัวอักษรจะดูเหมือนกันทุกประการ",

  "phrase.step": "ขั้นที่ 2 จาก 4",
  "phrase.title": "จดคำเหล่านี้ไว้",
  "phrase.sub": "ครั้งละสี่คำ ตามลำดับนี้ ตัวเลขเป็นส่วนหนึ่งของชุดคำ คำที่ถูกแต่อยู่ผิดตำแหน่งจะเปิดอะไรไม่ได้เลย",
  "phrase.screenshot": "อย่าถ่ายภาพหน้าจอนี้ ให้เขียนคำด้วยมือ หรือตอกลงบนแผ่นโลหะ",
  "phrase.range": "คำที่ {from}–{to} จาก {total}",
  "phrase.shownumber": "แสดงหมายเลขคำด้วย",
  "phrase.shownumber.b": "สำหรับตอกแผ่น TinySeed นับเริ่มจาก 1",
  "phrase.next": "สี่คำถัดไป",
  "phrase.print": "พิมพ์แบบฟอร์มสำหรับตอกแผ่นแทน",
  "phrase.english": "คำทั้ง 24 คำเป็นภาษาอังกฤษเสมอ แม้แอปจะแสดงเป็นภาษาไทย เพราะคุณต้องคัดลอกด้วยมือและพิมพ์กลับทีละตัวอักษร",

  "derive.step": "ขั้นที่ 3 จาก 4",
  "derive.title": "กำลังคำนวณกุญแจของคุณ",
  "derive.body": "ขั้นตอนนี้ใช้เวลาสามถึงสิบวินาที และจะใช้เวลาเท่านี้ทุกครั้งที่คุณเปิดที่เก็บ การรอคือการป้องกัน เพราะเป็นสิ่งที่ทำให้การไล่เดาหลายล้านครั้งเป็นไปไม่ได้จริงสำหรับคนที่เก็บโทรศัพท์เครื่องนี้ได้",
  "derive.keepawake": "เปิดหน้าจอค้างไว้และอยู่ในแอป ถ้าสลับไปแอปอื่น หน้าจอจะดับและต้องเริ่มคำนวณใหม่ตั้งแต่ต้น",
  "derive.where": "ใช้ Argon2id ทำงานด้วยจาวาสคริปต์ล้วนบนเครื่องนี้ ไม่มีการส่งข้อมูลออกไปที่ใด โทรศัพท์คำนวณทั้งหมดด้วยตัวเอง ซึ่งเป็นเหตุผลที่มันช้า",
  "derive.why": "ความช้านี้ตั้งใจให้เป็นเช่นนั้น เพราะเป็นสิ่งที่ทำให้คนอื่นเดาชุดคำของคุณไม่ได้ เปิดหน้าจอค้างไว้",
  "derive.s1": "ตรวจคำกับรายการคำศัพท์แล้ว",
  "derive.s2": "กำลังคำนวณกุญแจของที่เก็บ",
  "derive.s3": "ทดสอบตัวเอง ปิดผนึกและเปิดข้อมูลตัวอย่าง",

  "verify.step": "ขั้นที่ 4 จาก 4",
  "verify.title": "ยืนยันว่าคุณจดไว้แล้ว",
  "verify.body": "ทั้งยี่สิบสี่คำ ตามลำดับ พร้อมวลีรหัสผ่านของคุณ หน้านี้คือหน้าเดียวกับที่คุณจะเห็นทุกครั้งที่เปิดที่เก็บ จึงควรทำความคุ้นเคยตั้งแต่ตอนนี้",
  "verify.count": "ใส่คำแล้ว {n} จาก {total}",
  "verify.pending": "ยังตรวจสอบไม่ได้",
  "verify.checksumnote": "คำสุดท้ายทำหน้าที่เป็นค่าตรวจสอบ ตราบใดที่ยังใส่ไม่ครบยี่สิบสี่คำ แอปจะบอกได้แค่ว่าแต่ละคำมีอยู่จริงหรือไม่ แต่บอกไม่ได้ว่าชุดคำถูกต้องหรือไม่",
  "verify.submit": "ตรวจสอบและสร้างที่เก็บ",
  "verify.showagain": "ขอดูคำอีกครั้ง",

  "home.persisted": "พื้นที่จัดเก็บมั่นคง",
  "home.notpersisted": "พื้นที่จัดเก็บไม่รับประกัน",
  "home.count": "ข้อความที่ปิดผนึกไว้ {n} ข้อความ",
  "home.nopreview": "ไม่มีอะไรในหน้านี้ที่อ่านได้ แม้แต่ตัวคุณเอง สิ่งที่แสดงคือจำนวน ลำดับ และขนาดโดยประมาณ มากพอให้รู้ว่าที่เก็บยังอยู่ครบ และไม่มากไปกว่านั้น",
  "home.entry.meta": "ปิดผนึก · ประมาณ {size} · {date}",
  "home.write": "เขียน",
  "home.unlock": "ปลดล็อกเพื่ออ่าน",
  "home.backup": "สำรองข้อมูล",
  "home.restore": "กู้คืน",
  "home.settings": "ตั้งค่า",
  "home.vaults": "สลับที่เก็บ",
  "home.backup.days": "สำรองข้อมูลล่าสุด {n} วันที่แล้ว",
  "home.backup.one": "มีข้อความหนึ่งข้อความอยู่แค่ในเครื่องนี้",

  "write.title": "ข้อความใหม่",
  "write.seal": "ปิดผนึก",
  "write.for": "ถึง",
  "write.for.optional": "— ไม่บังคับ",
  "write.for.note": "ป้ายนี้ถูกปิดผนึกไปพร้อมกับข้อความ จึงอ่านไม่ได้จนกว่าที่เก็บจะถูกเปิด เป็นบันทึกถึงคนที่เข้ามาอ่าน ไม่ใช่การส่งอะไรออกไป",
  "write.chars": "{n} ตัวอักษร",
  "write.storedsize": "ขนาดที่จัดเก็บ",
  "write.padnote": "ทุกข้อความจะถูกเติมให้เป็นหนึ่งในสามขนาด เพื่อไม่ให้ความยาวของสิ่งที่คุณเขียนบอกอะไรกับใครได้ การเขียนไม่ต้องใช้ชุดคำ เพราะที่เก็บนี้เพิ่มข้อความได้เสมอ แต่จะอ่านไม่ได้เลยหากไม่มีชุดคำ",
  "write.thaicount": "ภาษาไทยหนึ่งตัวอักษรใช้พื้นที่มากกว่าภาษาอังกฤษเมื่อเข้ารหัสแบบ UTF-8 ตัวนับจึงนับตัวอักษรที่มองเห็น ส่วนขนาดที่จัดเก็บนับไบต์จริง",
  "write.sealed.title": "ปิดผนึกแล้ว",

  "unlock.title": "เปิดที่เก็บ",
  "unlock.mode.type": "พิมพ์คำ",
  "unlock.mode.grid": "ตารางแผ่น",
  "unlock.mode.numbers": "ตัวเลข",
  "unlock.passphrase": "วลีรหัสผ่าน",
  "unlock.passphrase.note": "ช่องว่างและตัวพิมพ์ใหญ่มีผลทั้งหมด ช่องนี้ไม่ใช่ช่องรหัสผ่านของเบราว์เซอร์ จึงไม่มีอะไรเสนอจะจดจำให้",
  "unlock.notaword": "ไม่ใช่คำใน BIP39",
  "unlock.numbering": "แผ่นของคุณใช้การนับแบบไหน",
  "unlock.numbering.note": "ถ้าเลือกผิด คำทุกคำจะเลื่อนไปหนึ่งตำแหน่ง ควรตรวจกับแผ่นที่คุณอ่านออกอยู่แล้วก่อนเชื่อ",
  "unlock.numbering.tiny.s": "เริ่มจาก 1",
  "unlock.numbering.bip39": "ดัชนี BIP39",
  "unlock.numbering.bip39.s": "เริ่มจาก 0",
  "unlock.numbering.current": "การนับ",
  "unlock.numbering.change": "เปลี่ยน",
  "unlock.grid.note": "แถวที่กำลังทำงานอยู่จะค้างอยู่ใต้นิ้วโป้งขณะเลื่อนรายการ และคำจะปรากฏทันทีที่ผลรวมของรูที่ตอกอยู่ในช่วงที่ใช้ได้",
  "unlock.grid.arabic": "ตัวเลขน้ำหนักและหมายเลขคำใช้เลขอารบิกเสมอ ไม่ใช้เลขไทย เพราะต้องตรงกับตัวเลขบนแผ่นโลหะที่อยู่ในมือคุณ",
  "unlock.grid.notset": "ยังไม่ระบุ",
  "unlock.grid.outofrange": "เกินช่วงที่ใช้ได้",
  "unlock.err.checksum.t": "คำทั้ง 24 คำนี้ไม่ใช่ชุดคำที่ถูกต้อง",
  "unlock.err.checksum.b": "คำสุดท้ายของชุดคำ BIP39 ทำหน้าที่ตรวจสอบอีกยี่สิบสามคำ การตรวจสอบนั้นไม่ผ่าน แปลว่ามีอย่างน้อยหนึ่งคำที่ผิดหรือสลับลำดับ ไม่ได้แปลว่าที่เก็บเสียหาย",
  "unlock.err.checksum.suspects": "ตำแหน่งที่ควรตรวจก่อน",
  "unlock.err.noattempts": "ไม่มีการนับจำนวนครั้งที่ลอง และไม่มีการล็อกบัญชี คุณลองใหม่ได้ไม่จำกัด ข้อจำกัดเดียวคือเวลาสามถึงสิบวินาทีต่อครั้ง",
  "unlock.err.back": "กลับไปแก้ไขคำของฉัน",
  "unlock.err.cannotget": "ถ้าเปิดไม่ได้เลยต้องทำอย่างไร",
  "unlock.err.pass.t": "คำถูกต้อง แต่วลีรหัสผ่านไม่ถูก",
  "unlock.err.other.t": "ชุดคำนี้เป็นของที่เก็บอื่น",

  "read.title": "เปิดอยู่",
  "read.relock": "จะล็อกอีกครั้งใน {time}",
  "read.locknow": "ล็อกเดี๋ยวนี้",
  "read.nolabel": "ไม่ได้ระบุผู้รับ",
  "read.when": "{date} · ข้อความที่ {n}",
  "read.norelease": "ไม่มีปุ่มคัดลอก แชร์ หรือส่งออกเป็นข้อความที่อ่านได้ เมื่อเวลาหมดลง หน้าจอจะกลับไปยังรายการที่ล็อกไว้ และกุญแจจะถูกทิ้ง การเข้ามาใหม่ต้องใช้ชุดคำอีกครั้ง",

  "blank.t": "ซ่อนไว้ขณะที่แอปอยู่เบื้องหลัง",
  "blank.b": "แตะเพื่อกลับเข้ามา สิ่งที่เปิดค้างไว้ถูกล็อกเรียบร้อยแล้ว",

  "backup.title": "สำรองข้อมูล",
  "restore.title": "กู้คืน",

  "set.title": "ตั้งค่า",
  "set.app": "แอปนี้",
  "set.relock": "ล็อกอีกครั้งหลังจาก",
  "set.relock.s": "ขณะที่มีข้อความเปิดอยู่บนหน้าจอ",
  "set.language": "ภาษา",
  "set.language.s": "เปลี่ยนทุกข้อความในแอป",
  "set.theme": "ธีม",
  "set.theme.s": "ตามระบบ หากไม่ได้ตั้งค่าไว้",
  "set.theme.auto": "อัตโนมัติ",
  "set.vault": "ที่เก็บนี้",
  "set.fp": "ลายนิ้วมือของที่เก็บ",
  "set.name": "ชื่อเล่น",
  "set.name.s": "ป้ายชื่อของที่เก็บนี้ในหน้าเลือกที่เก็บและในรายการ ชื่อนี้อยู่แค่ในเครื่องนี้และจะไม่ถูกเขียนลงไฟล์สำรอง ไฟล์สำรองไม่ควรบอกว่าที่เก็บนี้มีไว้เพื่ออะไร",
  "set.print": "พิมพ์ตาราง TinySeed",
  "set.print.s": "ต้องใช้ชุดคำของคุณ เพราะแอปไม่ได้เก็บไว้",
  "set.rekey": "เปลี่ยนวลีรหัสผ่าน",
  "set.rekey.s": "ต้องใช้ชุดคำ และไฟล์สำรองที่ทำไว้วันนี้",
  "set.rekey.b": "การเปลี่ยนวลีรหัสผ่านคือการปิดผนึกทุกข้อความใหม่ด้วยกุญแจใหม่ หากหยุดกลางคัน ไฟล์สำรองคือสิ่งที่ช่วยคุณไว้ แอปจึงบังคับให้ทำสำรองก่อน",
  "diag.title": "ข้อมูลวินิจฉัย",
  "diag.body": "ทุกสิ่งที่ตัดสินว่าแอปนี้ติดตั้งได้หรือไม่ และสิ่งที่คุณเขียนไว้จะอยู่รอดหรือไม่ สีแดงคือสิ่งที่มีปัญหา",
  "diag.share": "ไม่มีข้อมูลลับในหน้านี้ ไม่มีข้อความ ชุดคำ หรือวลีรหัสผ่านปรากฏอยู่ ถ่ายภาพหน้านี้ไว้ได้หากต้องการความช่วยเหลือ",
  "diag.open": "ข้อมูลวินิจฉัย",
  "set.version": "เวอร์ชัน",
  "set.version.app": "เวอร์ชันแอป",
  "set.version.hash": "ค่าแฮชของรุ่น",
  "set.checkupdate": "ตรวจหาการอัปเดต",
  "set.remove": "ลบที่เก็บนี้ออกจากเครื่อง",
  "set.remove.b": "ทุกอย่างในที่เก็บนี้จะถูกลบ ที่เก็บอื่นในเครื่องนี้ไม่ถูกแตะต้อง ไฟล์สำรองที่เก็บไว้ที่อื่นพร้อมกับชุดคำของคุณคือทางกลับทางเดียว ระบบจะให้พิมพ์ลายนิ้วมือของที่เก็บเพื่อยืนยัน",
  "set.irreversible": "ย้อนกลับไม่ได้",

  "print.title": "ชุดคำกู้คืน — แบบฟอร์มสำหรับตอกแผ่น",
  "print.sub": "Dying Message · BIP39 24 คำ · การจัดบิตแบบ TinySeed",
  "print.vault": "ที่เก็บ",
  "print.date": "วันที่",
  "print.word": "คำ",
  "print.sum": "ผลรวม",
  "print.foot": "หน้า {n} จาก {total} · พิมพ์เป็นขาวดำ · ไม่มีสีใดที่จำเป็นต่อความหมาย",
  "print.notes.title": "วิธีใช้แผ่นนี้",
  "print.badword": "แผ่นนี้ไม่ถูกพิมพ์ออกมา เพราะคำที่ {n} ไม่อยู่ในรายการ BIP39 แอปจึงคำนวณหมายเลขของคำนั้นไม่ได้ และแผ่นที่มีแถวว่างจะถูกตอกผิด กรุณาย้อนกลับไปตรวจชุดคำอีกครั้ง",
  "print.preview": "นี่คือแผ่นที่จะพิมพ์ออกมาจริงทุกประการ กรุณาตรวจคำกับหน้าจออีกครั้งก่อนลงมือตอก",

  "guide.title": "คู่มือ",
  "guide.what.t": "แอปนี้คืออะไร",
  "guide.what.b1": "เป็นที่สำหรับเขียนสิ่งที่คุณอยากให้มีคนได้อ่านหลังจากคุณจากไป และเพื่อให้แน่ใจว่าจะไม่มีใครอ่านได้ก่อนหน้านั้น",

  // ---- deliberately identical to English. Names, hostnames, BIP39 words and the standard
  // ---- library names are never translated; they are listed so the build reports no gap.
  "app.name": "Dying Message",
  "app.origin": "dyngmsg.home1ab.com",
  "common.words24": "canyon  orbit  velvet",
  "boot.idb": "IndexedDB",
  "unlock.numbering.tiny": "TinySeed",

  // ---- A: install gate
  "install.ios.body": "แอปจะเก็บข้อความไว้ในแอปที่ติดตั้งแล้ว ซึ่งเป็นที่ที่โทรศัพท์ปกป้องข้อมูลได้อย่างเหมาะสมและไม่ลบทิ้งเองโดยไม่บอก หากอยู่ในแท็บเบราว์เซอร์ จะไม่มีข้อใดเป็นจริงเลย",
  "install.ios.safarionly": "ใช้ Safari เท่านั้น Chrome, Firefox และ Edge บน iPhone ติดตั้งแอปนี้ไม่ได้ ไม่ว่าเมนูจะบอกอย่างไร ให้เปิดหน้านี้ใน Safari ก่อน",
  "install.ios.s1.t": "แตะปุ่มแชร์ที่ด้านล่างของ Safari",
  "install.ios.s1.b": "รูปสี่เหลี่ยมที่มีลูกศรชี้ขึ้นด้านบน บน iPad ปุ่มนี้จะอยู่ที่แถบด้านบนแทน",
  "install.ios.s2.t": "เลือก “เพิ่มไปยังหน้าจอโฮม”",
  "install.ios.s2.b": "อยู่ค่อนไปทางล่างของรายการสีเทา ให้เลื่อนผ่านแถวสำหรับแชร์ลงไป",
  "install.ios.s3.t": "แตะเพิ่ม แล้วเปิดจากหน้าจอโฮม",
  "install.ios.s3.b": "จะมีไอคอนใหม่ปรากฏขึ้น ทุกอย่างจากนี้ไปเกิดขึ้นในไอคอนนั้น ไม่ใช่ใน Safari",
  "install.android.body": "Chrome ทำได้ในแตะเดียว แอปที่ติดตั้งแล้วจะได้พื้นที่จัดเก็บที่ระบบจะไม่ลบทิ้งเอง ซึ่งแท็บธรรมดาไม่ได้",
  "install.android.button": "ติดตั้ง Dying Message",
  "install.android.fallback": "หากปุ่มนั้นไม่ทำงาน",
  "install.android.s1.t": "เปิดเมนู ⋮ ที่มุมขวาบน",
  "install.android.s1.b": "จุดสามจุดของ Chrome ข้างแถบที่อยู่เว็บ",
  "install.android.s2.t": "เลือก “ติดตั้งแอป” หรือ “เพิ่มไปยังหน้าจอหลัก”",
  "install.android.s2.b": "ข้อความต่างกันไปตามเวอร์ชันของ Chrome เลือกอันไหนก็ถูกต้องทั้งคู่",
  "install.android.s3.t": "ยืนยัน แล้วเปิดจากหน้าจอหลัก",
  "install.android.s3.b": "ไอคอนใหม่จะเปิดขึ้นโดยไม่มีแถบที่อยู่เว็บ นั่นคือวิธีรู้ว่าติดตั้งสำเร็จ",
  "install.android.shortcut": "เบราว์เซอร์บางตัวบน Android มี “เพิ่มไปยังหน้าจอหลัก” แต่สร้างเป็นทางลัดบุ๊กมาร์ก ไม่ใช่แอปที่ติดตั้งจริง ถ้าเปิดไอคอนแล้วเห็นแถบที่อยู่เว็บ แปลว่าเป็นทางลัด ให้ลบทิ้งแล้วใช้ Chrome",
  "install.desktop.body": "เมื่อติดตั้งแล้ว แอปจะได้พื้นที่จัดเก็บที่เบราว์เซอร์รับปากว่าจะเก็บไว้ และเปิดในหน้าต่างของตัวเอง ไม่มีแถบที่อยู่เว็บ ไม่มีส่วนขยาย และไม่มีแท็บอื่น ในแท็บธรรมดาไม่มีข้อใดเป็นจริง และที่เก็บที่สร้างไว้ในนั้นอาจถูกลบไปพร้อมกับการล้างข้อมูลการท่องเว็บตามปกติ",
  "install.desktop.s1.t": "หาไอคอนติดตั้งในแถบที่อยู่เว็บ",
  "install.desktop.s1.b": "อยู่ปลายด้านขวา ข้างรูปดาวบุ๊กมาร์ก ทั้ง Chrome และ Edge มีไอคอนนี้",
  "install.desktop.s2.t": "คลิกแล้วยืนยัน “ติดตั้ง”",
  "install.desktop.s2.b": "แอปจะเปิดในหน้าต่างของตัวเอง ไม่มีแท็บและไม่มีแถบที่อยู่เว็บ",
  "install.desktop.s3.t": "ปิดแท็บนี้ แล้วทำงานในหน้าต่างนั้นเท่านั้น",
  "install.desktop.s3.b": "สิ่งที่คุณทำในแท็บเบราว์เซอร์อยู่คนละส่วนกัน และจะสูญหายไป",
  "install.desktop.where.t": "ดูตรงไหน",
  "install.desktop.where.b": "ไอคอนติดตั้งอยู่ปลายด้านขวาของแถบที่อยู่เว็บ ใน Chrome เป็นรูปจอเล็กที่มีลูกศรชี้ลง ส่วนใน Edge เป็นเครื่องหมายบวกในกรอบสี่เหลี่ยม หากไม่มี แปลว่าหน้าเว็บยังโหลดไม่เสร็จ หรือเบราว์เซอร์นี้ไม่รองรับการติดตั้ง",
  "install.desktop.safari.t": "Safari บน Mac ทำสิ่งนี้ไม่ได้",
  "install.desktop.safari.b": "ให้ใช้ Chrome หรือ Edge บนคอมพิวเตอร์ คำสั่ง “เพิ่มไปยัง Dock” ของ Safari สร้างหน้าต่างแยกได้จริง แต่พฤติกรรมของพื้นที่จัดเก็บต่างออกไปมากพอที่แอปนี้จะไม่ยอมรับ",
  "install.eu.title": "การติดตั้งอาจไม่ได้ผลบน iPhone เครื่องนี้",
  "install.eu.body": "ในบางภูมิภาค iOS อนุญาตให้เบราว์เซอร์อื่นนอกจาก Safari แสดงผลหน้าเว็บได้ และแอปที่เพิ่มไปยังหน้าจอโฮมจากเบราว์เซอร์เหล่านั้นอาจเปิดขึ้นเป็นแท็บธรรมดา ไม่ใช่แอปที่ติดตั้งจริง",
  "install.eu.tell.t": "ตรวจสอบอย่างไร",
  "install.eu.tell.b": "เพิ่มไปยังหน้าจอโฮม แล้วเปิดไอคอนนั้น หากเห็นแถบที่อยู่เว็บหรือปุ่มควบคุมของเบราว์เซอร์ แปลว่าไม่ได้ติดตั้ง แต่เป็นบุ๊กมาร์ก และที่เก็บที่สร้างไว้ข้างในอาจถูกลบได้โดยไม่มีการเตือน",
  "install.eu.instead.t": "ควรทำอย่างไรแทน",
  "install.eu.o1": "เปิดหน้านี้ใน Safari แล้วติดตั้งจากที่นั่น เพราะ Safari ติดตั้งได้อย่างถูกต้องในทุกภูมิภาค",
  "install.eu.o2": "หากเครื่องของคุณมีให้เลือกเฉพาะเบราว์เซอร์อื่น ให้ใช้โทรศัพท์เครื่องอื่นหรือคอมพิวเตอร์ สำหรับที่เก็บที่คุณตั้งใจจะเก็บไว้จริง",
  "install.eu.o3": "ไม่ว่าจะอย่างไร อย่าสร้างที่เก็บ อย่าเขียนข้อความ และอย่าจดชุดคำจากในแท็บ เพราะมันจะสูญหาย และคุณจะเข้าใจว่ามันปลอดภัย",
  "install.eu.nofix": "นี่ไม่ใช่ข้อจำกัดที่แอปจะหลบเลี่ยงได้ และไม่ควรหลบเลี่ยงด้วย การออกแบบทั้งหมดตั้งอยู่บนพื้นที่จัดเก็บที่ระบบรับปากว่าจะเก็บไว้ หากไม่มีคำรับปากนั้น ที่เก็บก็เป็นที่เก็บแต่เพียงในชื่อ",
  "install.eu.showsafari": "ขอดูขั้นตอนของ Safari",
  "install.already.b": "ปิดแท็บนี้ แล้วเปิด Dying Message จากหน้าจอโฮม ที่เก็บของคุณอยู่ในนั้น ไม่ได้อยู่ที่นี่",
  "install.already.desktop": "ปิดแท็บนี้ แล้วเปิด Dying Message จากรายการแอป Dock หรือเมนูเริ่ม ที่เก็บของคุณอยู่ในนั้น ไม่ได้อยู่ที่นี่",
  "install.foot": "dyngmsg.home1ab.com · ไม่มีการส่งข้อมูลไปยังที่อยู่นี้อีกเลยหลังการโหลดครั้งแรก",

  // ---- B: boot states
  "boot.explain": "ทุกรายการด้านล่างจะถูกตรวจก่อนที่อะไรจะเปิดขึ้น หากมีข้อใดไม่ผ่าน แอปจะหยุดและบอกให้ทราบ แทนที่จะทำงานต่อแล้วทำข้อมูลสูญหาย",
  "boot.c.secure": "การเชื่อมต่อที่ปลอดภัย",
  "boot.c.selftest": "ทดสอบระบบเข้ารหัสด้วยตัวเอง",
  "boot.c.standalone": "ทำงานในฐานะแอปที่ติดตั้งแล้ว",
  "boot.c.storage": "พื้นที่จัดเก็บพร้อมใช้งาน",
  "boot.c.persist": "ได้รับสิทธิ์เก็บข้อมูลถาวร",
  "boot.c.read": "กำลังอ่านที่เก็บ",
  "boot.c.seals": "กำลังตรวจผนึกของแต่ละข้อความ",
  "boot.yes": "ใช่",
  "boot.no": "ไม่",
  "boot.deferred": "ตรวจตอนปลดล็อก",

  "crash.title": "มีบางอย่างในแอปทำงานผิดพลาด",
  "crash.body": "ที่เก็บของคุณไม่ได้ถูกเปลี่ยนแปลง ไม่มีอะไรสูญหาย นี่คือความผิดพลาดของตัวแอป ไม่ใช่ของข้อมูล หากทำได้ กรุณาจดหรือถ่ายภาพข้อความด้านล่างไว้ก่อนโหลดใหม่ เพราะเป็นบันทึกเพียงชิ้นเดียว เนื่องจากแอปนี้ไม่ส่งรายงานไปยังที่ใดทั้งสิ้น",
  "crash.where": "สิ่งที่ผิดพลาด",
  "crash.reload": "โหลดแอปใหม่",
  "crash.safe": "ด้านล่างนี้ไม่มีข้อความ ชุดคำ หรือวลีรหัสผ่านของคุณแสดงอยู่ และจะไม่มีการเขียนสิ่งเหล่านั้นลงหน้าจอนี้เลย",
  "selftest.title": "แอปรุ่นนี้ไม่สมบูรณ์",
  "selftest.body": "Argon2id ให้ผลลัพธ์ไม่ตรงกับที่มาตรฐานกำหนดไว้ แปลว่าโค้ดบนเครื่องนี้ถูกแก้ไขหรือเสียหาย แอปจะไม่แตะต้องที่เก็บของคุณในสภาพนี้",
  "selftest.what": "ให้ติดตั้งใหม่จาก dyngmsg.home1ab.com แล้วเทียบค่าแฮชของรุ่นกับที่ประกาศไว้ที่นั่น ที่เก็บและไฟล์สำรองของคุณไม่ได้รับผลกระทบ เรื่องนี้เกี่ยวกับตัวแอป ไม่ใช่ข้อมูล",

  "insecure.title": "แอปนี้ไม่ได้ถูกส่งมาอย่างปลอดภัย",
  "insecure.body": "ที่อยู่เว็บต้องขึ้นต้นด้วย https และมีใบรับรองที่ถูกต้อง หากเป็น http ธรรมดา เบราว์เซอร์จะไม่รับปากว่าจะเก็บสิ่งที่แอปนี้บันทึกไว้ ที่เก็บที่สร้างขึ้นที่นี่จึงอาจถูกลบเมื่อใดก็ได้โดยไม่มีการเตือน และคุณจะไม่รู้เลยจนถึงวันที่ต้องการอ่าน",
  "insecure.what": "สิ่งที่ขาดไป",
  "insecure.w1": "ไม่สามารถแม้แต่จะขอสิทธิ์เก็บข้อมูลถาวรได้ จึงไม่มีอะไรได้รับการป้องกันจากการถูกล้าง",
  "insecure.w2": "service worker ทำงานไม่ได้ แอปจึงใช้งานออฟไลน์ไม่ได้",
  "insecure.w3": "เบราว์เซอร์จะไม่ติดตั้งแอป แต่จะสร้างเพียงทางลัดบุ๊กมาร์กเท่านั้น",
  "insecure.fix": "เรื่องนี้ต้องให้ผู้เผยแพร่แอปแก้ไขที่ตัวโดเมน ไม่มีการตั้งค่าใดในเครื่องของคุณที่จะทำให้ที่อยู่แบบ http ปลอดภัยพอจะเก็บที่เก็บได้",
  "nostore.title": "เครื่องนี้ไม่ยอมให้แอปเก็บข้อมูลใดเลย",
  "nostore.body": "แอปเปิดหรือสร้างที่เก็บที่นี่ไม่ได้ ไม่มีอะไรเสียหาย เพียงแต่ไม่มีที่ให้เก็บสิ่งที่คุณเขียน แอปจึงจะไม่แสร้งทำเป็นว่ามี",
  "nostore.causes.t": "มักเป็นข้อใดข้อหนึ่งต่อไปนี้",
  "nostore.c1": "หน้าต่างส่วนตัวหรือโหมดไม่ระบุตัวตน ให้ปิดแล้วเปิดแอปตามปกติ",
  "nostore.c2": "ข้อมูลเว็บไซต์ของที่อยู่นี้ถูกบล็อกไว้ในการตั้งค่าเบราว์เซอร์",
  "nostore.c3": "นโยบายการจัดการอุปกรณ์ ซึ่งพบบ่อยในโทรศัพท์และคอมพิวเตอร์ของที่ทำงาน",
  "nostore.c4": "เครื่องมีพื้นที่เหลือไม่พอจริง ๆ",
  "nostore.elsewhere": "หากคุณมีที่เก็บอยู่แล้วบนเครื่องอื่น ที่เก็บนั้นไม่ได้รับผลกระทบ หน้านี้ไม่ได้บอกอะไรเกี่ยวกับมันเลย",
  "nostore.diag": "ข้อมูลวินิจฉัย",
  "nostore.noway": "ไม่มีทางข้ามหน้านี้ไปได้ และนั่นเป็นความตั้งใจ",

  "twocopies.strip": "มีที่เก็บอีกชุดหนึ่งอยู่ในเบราว์เซอร์ของคุณ แอปที่ติดตั้งนี้ไม่ได้แสดงที่เก็บนั้น",
  "twocopies.title": "คุณมีสำเนาแยกกันสองชุด",
  "twocopies.body": "มีการสร้างที่เก็บไว้ในเบราว์เซอร์ก่อนที่จะติดตั้งแอป เบราว์เซอร์และแอปที่ติดตั้งแยกพื้นที่จัดเก็บออกจากกัน สิ่งที่คุณสร้างไว้ที่นั่นจึงไม่ได้อยู่ที่นี่ และก็ไม่ได้สูญหายไปไหนเช่นกัน",
  "twocopies.here": "ที่นี่",
  "twocopies.here.s": "แอปที่ติดตั้งแล้ว",
  "twocopies.browser": "เบราว์เซอร์",
  "twocopies.how": "วิธีย้ายที่เก็บจากเบราว์เซอร์มาที่นี่ ให้เปิดแอปใน Safari ส่งออกไฟล์สำรองจากที่นั่น แล้วกู้คืนไฟล์นั้นที่นี่ ที่เก็บทั้งสองมีชุดคำของตัวเอง และแอปจะไม่ยอมรวมเข้าด้วยกัน เพราะจะกลายเป็นสองที่เก็บวางคู่กัน",
  "twocopies.continue": "ใช้ที่เก็บในเครื่องนี้ต่อไป",
  "twocopies.persistent": "แถบนี้จะปรากฏทุกครั้งที่เปิดแอป จนกว่าจะจัดการสำเนาในเบราว์เซอร์เรียบร้อย และปิดแถบนี้ไม่ได้",

  "damaged.title": "ที่เก็บนี้เสียหายบางส่วน",
  "damaged.body": "ข้อความ {bad} จาก {total} ข้อความไม่ตรงกับผนึกของตัวเองแล้ว กรณีนี้เกิดขึ้นเมื่อการเขียนข้อมูลถูกขัดจังหวะกลางคัน เช่น เครื่องมีพื้นที่ไม่พอ หรือถูกปิดแอปขณะกำลังบันทึก ไม่ใช่สัญญาณว่ามีใครเข้ามาแตะต้อง",
  "damaged.ok": "ผนึกสมบูรณ์",
  "damaged.bad": "ไม่ตรงกับผนึกของตัวเอง",
  "damaged.restorefirst": "ข้อความที่ยังสมบูรณ์ยังอ่านได้และไม่ถูกแตะต้อง การกู้คืนไฟล์สำรองจะเพิ่มสิ่งที่อยู่ในไฟล์กลับเข้ามาโดยไม่รบกวนข้อความเหล่านั้น การกู้คืนจึงควรลองก่อนเสมอ",
  "damaged.norepair": "ข้อความที่เสียหายซ่อมไม่ได้ การเข้ารหัสไม่มีทางเดาได้ว่าไบต์ที่เปลี่ยนไปเคยเป็นอะไร หากไม่มีไฟล์สำรองเก็บไว้ ก็คือหายไปแล้ว",
  "damaged.restore": "กู้คืนจากไฟล์สำรอง",
  "damaged.continue": "ใช้ข้อความที่ยังสมบูรณ์ต่อไป",
  "damaged.stay": "ข้อความที่เสียหายจะยังอยู่ในรายการพร้อมเครื่องหมายกำกับ จนกว่าคุณจะลบเอง แอปจะไม่ลบอะไรแทนคุณ",

  "update.title": "มีเวอร์ชันใหม่รออยู่",
  "update.body": "ดาวน์โหลดไว้แล้วแต่ยังไม่ได้ติดตั้ง แอปนี้จะไม่อัปเดตตัวเองลับหลังคุณ เพราะโค้ดที่ดูแลข้อความของคุณจะไม่เปลี่ยนจนกว่าคุณจะอนุญาต",
  "update.running": "กำลังใช้งานอยู่",
  "update.waiting": "รออยู่",
  "update.hash": "ค่าแฮชของรุ่น",
  "update.verify": "เทียบค่าแฮชกับที่ประกาศไว้ในหน้าโครงการก่อนอนุมัติ หากไม่ตรงกัน ให้ปฏิเสธและอย่าใช้แอปจนกว่าจะทราบสาเหตุ",
  "update.approve": "อนุมัติและเริ่มใหม่",
  "update.later": "ไว้ก่อน — ใช้เวอร์ชันนี้ต่อไป",
  "update.safe": "ที่เก็บของคุณไม่ถูกแตะต้องไม่ว่าจะเลือกทางใด การอัปเดตเปลี่ยนเฉพาะตัวแอป ไม่ใช่ข้อมูล",
  "update.none": "ไม่มีการอัปเดตรออยู่ แอปนี้กำลังใช้โค้ดรุ่นใหม่ที่สุดที่มี",

  // ---- language
  "lang.step": "ขั้นที่ 0 จาก 4",
  "lang.th.s": "ไทย — ตรวจพบจากเครื่องนี้",
  "lang.en.s": "อังกฤษ",

  // ---- C2: passphrase
  "pass.step": "ขั้นที่ 1 จาก 4",
  "pass.body": "วลีรหัสผ่านคือความลับชิ้นที่สอง เก็บแยกจากคำทั้ง 24 คำ ต้องใช้ทั้งสองอย่างจึงจะเปิดที่เก็บได้ อย่างใดอย่างหนึ่งเพียงลำพังทำอะไรไม่ได้เลย",
  "pass.split": "วิธีนี้ทำให้คุณแบ่งความลับให้คนสองคนถือไว้คนละครึ่งได้ มอบคำที่ตอกบนแผ่นโลหะให้น้องสาว และมอบวลีรหัสผ่านบนกระดาษให้ทนาย ทั้งสองคนจะอ่านข้อความของคุณตามลำพังไม่ได้ แต่ก็หมายความว่าหากฝ่ายใดฝ่ายหนึ่งทำส่วนของตนหาย จะไม่มีใครได้อ่านเลย โปรดเลือกอย่างตั้งใจ",
  "pass.off.t": "ไม่ใช้วลีรหัสผ่าน",
  "pass.off.b": "ใช้คำ 24 คำเพียงอย่างเดียวในการเปิดที่เก็บ ส่งต่อได้ง่ายที่สุด และมีความลับเพียงชิ้นเดียวให้ดูแล",
  "pass.gen.t": "ให้แอปเลือกคำให้ห้าคำ",
  "pass.gen.b": "สุ่มจากรายการคำชุดเดียวกัน คัดลอกด้วยมือง่ายกว่ารหัสผ่าน และเดาไม่ได้",
  "pass.gen.redraw": "สุ่มใหม่อีกห้าคำ",
  "pass.gen.note": "คุณจะต้องพิมพ์คำเหล่านี้กลับเข้าไปก่อนที่ที่เก็บจะถูกสร้าง ที่นี่ไม่มีปุ่มคัดลอก และจะไม่มีในภายหลังด้วย",
  "pass.own.t": "ใช้วลีรหัสผ่านของฉันเอง",
  "pass.own.b": "อย่างน้อย 12 ตัวอักษร และควรเป็นข้อความที่คุณไม่เคยพิมพ์ไว้ที่อื่นมาก่อน",
  "pass.own.short": "สั้นเกินไป — ต้องมีอย่างน้อย 12 ตัวอักษร",
  "pass.own.weak": "ยังไม่แข็งแรงพอ ยาวขึ้นดีกว่าแปลกขึ้น",
  "pass.own.ok": "แข็งแรงพอแล้ว ยาวขึ้นดีกว่าแปลกขึ้น",
  "pass.nfkd": "ช่องว่าง ตัวพิมพ์ใหญ่ และเครื่องหมายเสริมสระ มีผลทั้งหมด ตรงตามที่พิมพ์ ข้อความจะถูกจัดรูปแบบมาตรฐาน (NFKD) แต่ไม่ถูกเปลี่ยนแปลงอย่างอื่น “Bangkok 2019” กับ “bangkok 2019” เป็นความลับคนละชุดกัน",
  "pass.locked": "ตัวเลือกนี้เปลี่ยนภายหลังไม่ได้ นอกจากจะทำกุญแจใหม่ให้ทั้งที่เก็บ",

  // ---- C3 / C6 / C5 / C7
  "phrase.last": "ฉันจดครบทั้ง 24 คำแล้ว",
  "derive.failed": "ขั้นตอนนี้ทำไม่สำเร็จ ไม่มีอะไรถูกเปลี่ยนแปลง กรุณาลองใหม่",
  "derive.elapsed": "{n} วินาที",
  "derive.unknown": "ขั้นตอนนี้ไม่มีตัวเลขความคืบหน้า เวลาที่ผ่านไปจึงเป็นตัวชี้วัดเดียวที่ตรงความจริง",
  "derive.opening": "กำลังเปิด",
  "derive.opening.body": "ใช้เวลาสามถึงสิบวินาที แอปยังไม่รู้ว่าชุดคำของคุณถูกต้องหรือไม่ เพราะต้องคำนวณทั้งหมดนี้ให้เสร็จก่อน และนั่นคือสิ่งที่ทำให้การไล่เดาเป็นไปไม่ได้จริง",
  "derive.opening.keepon": "เปิดหน้าจอค้างไว้ การสลับไปแอปอื่นจะทำให้หน้าจอดับและยกเลิกการคำนวณนี้",
  "derive.opening.state": "24 คำ · {pass}",
  "derive.opening.passset": "ตั้งวลีรหัสผ่านไว้",
  "derive.opening.passnone": "ไม่ได้ตั้งวลีรหัสผ่าน",
  "derive.opening.gone": "คำของคุณออกจากช่องกรอกและออกจากหน้าจอไปแล้ว คำเหล่านั้นมีอยู่เฉพาะในการคำนวณนี้ และจะหายไปทันทีที่การคำนวณจบลง ไม่ว่าจะสำเร็จหรือไม่",
  "derive.cancel": "ยกเลิก",
  "derive.bench": "กำลังวัดความเร็วของเครื่องนี้ เพื่อให้ที่เก็บช้าได้มากที่สุดเท่าที่ยังใช้งานได้จริง",
  "verify.mismatch": "คำเหล่านี้ไม่ใช่คำที่แอปเพิ่งให้คุณไป กรุณาย้อนกลับไปอ่านอีกครั้ง แล้วพิมพ์ใหม่",

  "done.title": "ที่เก็บของคุณถูกสร้างแล้ว",
  "done.body": "ที่เก็บอยู่ในโทรศัพท์เครื่องนี้และไม่มีที่อื่น คำที่คุณจดไว้คือทางเดียวที่จะกลับเข้าไปได้ และแอปได้ลืมคำเหล่านั้นไปเรียบร้อยแล้ว",
  "done.fp": "ลายนิ้วมือของที่เก็บ",
  "done.fp.note": "จดค่านี้ไว้ข้างชุดคำของคุณ ภายหลังมันจะบอกได้ว่าไฟล์สำรองกับชุดคำเป็นของที่เก็บเดียวกันหรือไม่ ตัวมันเองไม่เปิดเผยอะไรเลย",
  "done.left.t": "เหลืออีกอย่างเดียว",
  "done.left.b": "บันทึกไฟล์สำรองไว้ที่อื่น เช่น อีกเครื่องหนึ่ง ไดรฟ์ หรือโฟลเดอร์บนคลาวด์ ไฟล์นี้เก็บเฉพาะข้อมูลที่เข้ารหัสแล้วและใช้ไม่ได้เลยหากไม่มีชุดคำของคุณ จึงเก็บไว้ที่ไหนก็ได้แทบทุกที่",
  "done.backup": "บันทึกไฟล์สำรองเดี๋ยวนี้",
  "done.print": "พิมพ์แบบฟอร์มสำหรับตอกแผ่น",
  "done.print.note": "ต้องใช้ชุดคำที่คุณเพิ่งยืนยัน ซึ่งยังอยู่ในหน่วยความจำอีกเพียงไม่กี่วินาที",
  "done.skip": "ข้ามไปก่อน",
  "done.skip.note": "การข้ามจะทิ้งแถบสีแดง “ยังไม่เคยสำรองข้อมูล” ไว้บนหน้าหลักจนกว่าคุณจะทำ และแถบนั้นไม่มีปุ่มปิด",

  // ---- D: home
  "home.persist.ask": "ขอสิทธิ์เก็บข้อมูลถาวรอีกครั้ง",
  "home.persist.body": "โทรศัพท์เครื่องนี้ยังไม่ได้รับปากว่าจะเก็บที่เก็บไว้ หากพื้นที่เหลือน้อย ระบบอาจลบทิ้งโดยไม่ถาม การเพิ่มแอปไปยังหน้าจอหลักมักช่วยแก้ปัญหานี้ได้",
  "home.count.one": "ข้อความที่ปิดผนึกไว้ 1 ข้อความ",
  "home.nothing.t": "ยังไม่มีข้อความที่ปิดผนึก",
  "home.nothing.b": "เมื่อคุณเขียนอะไรลงไป มันจะปรากฏที่นี่เป็นบรรทัดที่มีหมายเลขแต่ไม่มีข้อความ นั่นไม่ใช่ข้อผิดพลาด แอปอ่านสิ่งที่คุณเขียนไม่ได้จริง ๆ จนกว่าจะใส่ชุดคำ",
  "home.entry.bad": "ไม่ตรงกับผนึก · ประมาณ {size} · {date}",
  "home.emptydisabled": "ปุ่มปลดล็อกและสำรองข้อมูลจะยังใช้ไม่ได้ขณะที่ที่เก็บว่างเปล่า เพราะยังไม่มีอะไรให้เปิดหรือให้บันทึก",
  "home.backup.never": "ยังไม่เคยสำรองข้อมูล",
  "home.backup.never.s": "ที่เก็บนี้มีอยู่เพียงที่เดียวเท่านั้น",
  "home.backup.today": "สำรองข้อมูลแล้ววันนี้",
  "home.backup.fine": "ไม่มีอะไรต้องทำ",
  "home.backup.stale": "ข้อความที่ใหม่กว่านั้นอยู่แค่ในเครื่องนี้",
  "home.backup.urgent": "หากโทรศัพท์เครื่องนี้หายไปวันนี้ ที่เก็บส่วนใหญ่จะหายไปด้วย",
  "home.backup.some": "มีข้อความ {n} ข้อความอยู่แค่ในเครื่องนี้",

  // ---- E: write
  "write.toolong": "ยาวเกินขนาดใหญ่ที่สุด กรุณาย่อให้สั้นลง หรือแยกเป็นสองข้อความ",
  "write.empty": "กรุณาเขียนข้อความก่อน",
  "write.sealed.body": "มีเพียงชุดคำเท่านั้นที่เปิดข้อความนี้ได้ นี่คือข้อความที่ {n} ในที่เก็บของคุณ และจากนี้ไปทั้งแอปและตัวคุณเองจะไม่เห็นเนื้อความ จนกว่าจะใส่คำครบทั้งยี่สิบสี่คำ",
  "write.sealed.stale": "ไฟล์สำรองล่าสุดของคุณทำไว้เมื่อ {n} วันที่แล้ว และไม่มีข้อความนี้อยู่ กรุณาบันทึกไฟล์ใหม่ก่อนวางโทรศัพท์ลง",
  "write.sealed.never": "ยังไม่มีไฟล์สำรองของที่เก็บนี้เลย กรุณาบันทึกสักไฟล์ก่อนวางโทรศัพท์ลง",
  "write.backupnow": "สำรองข้อมูลเดี๋ยวนี้",
  "write.another": "เขียนอีกข้อความ",

  // ---- F: unlock
  "unlock.body": "ใส่คำทั้งยี่สิบสี่คำตามลำดับ แล้วตามด้วยวลีรหัสผ่าน จะยังไม่มีการตรวจสอบใดจนกว่าคำสุดท้ายจะครบ",
  "unlock.nomask": "เบราว์เซอร์นี้ซ่อนวลีรหัสผ่านไม่ได้ นอกจากจะใช้ช่องรหัสผ่าน ซึ่งจะทำให้มีสิ่งเสนอจะจดจำไว้ให้ ข้อความจึงยังมองเห็นอยู่ ให้บังหน้าจอแทน",
  "unlock.reveal": "แสดงวลีรหัสผ่าน",
  "unlock.hide": "ซ่อนวลีรหัสผ่าน",
  "unlock.submit": "เปิด — ใส่แล้ว {n} จาก 24 คำ",
  "unlock.submit.ready": "เปิดที่เก็บ",
  "unlock.leave": "การเปิดใช้เวลาสามถึงสิบวินาที การออกจากหน้านี้จะล้างทุกอย่างที่คุณพิมพ์ไว้",
  "unlock.suggestion": "คำที่ {n} — คำที่แนะนำ",
  "unlock.paste.warn": "วางคำลงครบทั้ง 24 ช่องแล้ว ชุดคำที่เคยผ่านคลิปบอร์ดถือว่าไม่เป็นความลับอีกต่อไป ควรถือว่าถูกเปิดเผยแล้ว และย้ายที่เก็บเมื่อทำได้",
  "unlock.grid.rowbad": "แถวที่ {n} เกินช่วงที่ใช้ได้ ค่า {sum} มากกว่า 2048 จึงเป็นคำไม่ได้ ลองตรวจดูว่ารูที่ตอกในคอลัมน์ 1024 ตั้งใจจะตอกที่คอลัมน์ 16 หรือไม่",
  "unlock.grid.clear": "ล้างแถวที่ {n}",
  "unlock.submit.outofrange": "เปิด — มีตัวเลขหนึ่งค่าเกินช่วงที่ใช้ได้",
  "unlock.err.checksum.why.last": "คำสุดท้ายเก็บค่าตรวจสอบ ความผิดพลาดที่ใดก็ตามจะแสดงผลที่นี่",
  "unlock.err.checksum.why.near": "คำนี้ต่างจากคำข้างเคียงในรายการเพียงหนึ่งบิต จึงอ่านผิดจากแผ่นโลหะได้ง่าย",
  "unlock.err.checksum.note": "ตำแหน่งเหล่านี้คือตำแหน่งที่มีโอกาสผิดมากที่สุด แอปบอกคำที่ถูกต้องให้ไม่ได้ เพราะแอปไม่รู้ หากทุกตำแหน่งดูถูกต้องแล้ว ความผิดพลาดมักเกิดจากการสลับลำดับของสองแถวที่อยู่ติดกัน",
  "unlock.err.pass.b": "คำทั้งยี่สิบสี่คำประกอบเป็นชุดคำที่ถูกต้อง แต่กุญแจที่ได้จากคำเหล่านั้นเปิดที่เก็บนี้ไม่ได้ เมื่อมีการตั้งวลีรหัสผ่านไว้ กรณีนี้เกือบทั้งหมดหมายความว่าวลีรหัสผ่านไม่ถูกต้อง",
  "unlock.err.pass.things": "สิ่งที่ทำให้วลีรหัสผ่านเปลี่ยนไป",
  "unlock.err.pass.t1": "ตัวพิมพ์ใหญ่ที่ต้นข้อความ ซึ่งแป้นพิมพ์เติมให้เอง",
  "unlock.err.pass.t2": "ช่องว่างที่ติดมาท้ายข้อความ มักเกิดจากการวางหรือการแก้คำอัตโนมัติ",
  "unlock.err.pass.t3": "เครื่องหมายคำพูดตรงที่ถูกเปลี่ยนเป็นแบบโค้ง",
  "unlock.err.pass.t4": "แป้นพิมพ์ภาษาไทยที่ให้สระและวรรณยุกต์หน้าตาเหมือนกัน แต่ลำดับการพิมพ์ต่างกัน",
  "unlock.err.pass.t5": "คำที่แอปสุ่มให้ห้าคำ ถูกคั่นด้วยช่องว่างสองช่องแทนที่จะเป็นช่องเดียว",
  "unlock.err.pass.empty": "หากคุณไม่เคยตั้งวลีรหัสผ่านให้ที่เก็บนี้ ให้เว้นช่องนี้ว่างสนิท อย่าพิมพ์ช่องว่าง เพราะช่องว่างเปล่ากับช่องว่างหนึ่งตัวเป็นความลับคนละชุดกัน",
  "unlock.err.pass.kept": "คำของคุณยังอยู่ครบ มีเพียงช่องวลีรหัสผ่านที่ถูกล้าง คุณจึงไม่ต้องเริ่มใหม่ทั้งหมด",
  "unlock.err.pass.retry": "ลองใส่วลีรหัสผ่านอีกครั้ง",
  "unlock.err.pass.stop": "หยุดไว้ก่อน",
  "unlock.err.other.b": "ชุดคำถูกต้อง และกุญแจที่ได้ก็เป็นกุญแจของที่เก็บจริง เพียงแต่ไม่ใช่ที่เก็บนี้ ไม่มีอะไรผิดปกติทั้งสองฝ่าย เป็นไปได้มากว่าคุณกำลังถือชุดคำของที่เก็บอีกอันที่คุณเคยสร้างไว้",
  "unlock.err.other.here": "เครื่องนี้เก็บ",
  "unlock.err.other.yours": "ชุดคำของคุณเปิด",
  "unlock.err.other.note": "ลายนิ้วมือคำนวณจากกุญแจ ไม่ได้คำนวณจากคำของคุณ การแสดงค่านี้จึงไม่เปิดเผยอะไร และเป็นวิธีที่เร็วที่สุดในการแยกที่เก็บสองอันออกจากกัน",
  "unlock.err.other.restore": "กู้คืนที่เก็บนั้นจากไฟล์",
  "unlock.err.other.retry": "ลองชุดคำอื่น",

  // ---- F5: read
  "read.sub": "ข้อความ {n} ข้อความ เรียงจากใหม่ไปเก่า ไม่มีอะไรออกจากหน้าจอนี้",
  "read.sub.one": "ข้อความ 1 ข้อความ ไม่มีอะไรออกจากหน้าจอนี้",
  "read.extend": "ขอเวลาเพิ่มอีกสองนาที",
  "read.tapread": "แตะเพื่ออ่าน — {size} ยาวกว่าข้อความอื่น",
  "read.damaged": "ข้อความนี้ไม่ตรงกับผนึกของตัวเอง จึงเปิดไม่ได้",
  "read.delete": "ลบข้อความนี้",
  "read.sr.relock": "ที่เก็บจะล็อกอีกครั้งใน {n} วินาที",
  "read.keys": "↑↓ เลื่อน · Enter เปิด · Esc ล็อก",

  // ---- G: backup and restore
  "backup.headline": "ไฟล์เดียว ยังปิดผนึกอยู่",
  "backup.body": "ไฟล์นี้เก็บข้อความของคุณตามที่จัดเก็บไว้ที่นี่ทุกประการ คือเข้ารหัสไว้ ไม่มีชุดคำ ไม่มีวลีรหัสผ่าน และไม่มีกุญแจอยู่ในไฟล์ คนที่เก็บไฟล์นี้ได้จะรู้เพียงว่าคุณเขียนไว้กี่ข้อความและยาวคร่าว ๆ เท่าไร ไม่มีอย่างอื่น",
  "backup.filemeta": "{size} · {n} ข้อความ · ปิดผนึก",
  "backup.filemeta.one": "{size} · 1 ข้อความ · ปิดผนึก",
  "backup.fpname": "ลายนิ้วมืออยู่ในชื่อไฟล์ เพื่อให้ภายหลังคุณรู้ได้ว่าไฟล์เป็นของที่เก็บใด โดยไม่ต้องเปิดอะไรเลย",
  "backup.where": "เก็บไว้ในที่ธรรมดาและทนทาน เช่น ไดรฟ์บนคลาวด์ อีเมลถึงตัวเอง หรือ USB ในลิ้นชัก การเก็บไว้ข้างชุดคำที่จดไว้ทำให้เสียความหมายทั้งหมด ให้แยกสองอย่างนี้ออกจากกัน",
  "backup.share": "แชร์ไฟล์",
  "backup.download": "ดาวน์โหลด",
  "backup.sharenote": "จะเปิดแผงแชร์ของโทรศัพท์ บนคอมพิวเตอร์ปุ่มนี้จะขึ้นว่าดาวน์โหลดแทน",
  "backup.saved": "บันทึกแล้ว แถบแจ้งเตือนการสำรองข้อมูลนับใหม่ตั้งแต่วันนี้",
  "backup.failed": "ไฟล์ยังไม่ถูกบันทึก ไม่มีอะไรเปลี่ยนแปลง กรุณาลองใหม่",

  "restore.choose": "เลือกไฟล์สำรอง",
  "restore.nophrase": "การกู้คืนไม่ถามชุดคำของคุณเลย ไฟล์ยังคงปิดผนึกอยู่ แอปเพียงตรวจว่าเป็นไฟล์สำรองจริงและเป็นของที่เก็บใด",
  "restore.pick": "เลือกไฟล์",
  "restore.pick.s": "ไฟล์ .dmv จากเครื่องนี้หรือจากไดรฟ์บนคลาวด์",
  "restore.checks": "สิ่งที่ตรวจก่อนจะเปลี่ยนแปลงอะไร",
  "restore.c1": "ไฟล์เป็นไฟล์สำรองของ Dying Message ไม่ใช่ไฟล์อื่น",
  "restore.c2": "โครงสร้างภายในครบถ้วนและไม่ถูกตัดทอน",
  "restore.c3": "ไฟล์เป็นของที่เก็บที่มีลายนิ้วมือใด",
  "restore.c4": "ในไฟล์มีข้อความกี่รายการที่เครื่องนี้ยังไม่มี",
  "restore.safe": "การกู้คืนจะไม่ลบหรือเขียนทับสิ่งที่มีอยู่แล้วในเครื่องนี้ กรณีแย่ที่สุดคือคุณได้ข้อความที่ไม่ต้องการเพิ่มมา ซึ่งลบออกทีหลังได้",
  "restore.multidevice": "การใส่ชุดคำเดียวกันบนเครื่องที่สองแล้วกู้คืนไฟล์สำรองที่นี่ คือวิธีที่ทำให้ที่เก็บเดียวอยู่ได้สองที่",
  "restore.new.t": "ที่เก็บนี้ยังไม่มีในเครื่องนี้",
  "restore.new.b": "ไฟล์นี้จะกลายเป็นที่เก็บอีกแห่งบนเครื่องนี้ เหมือนตอนที่ทำไฟล์สำรองไว้ทุกประการ คุณจะต้องใช้คำ 24 คำของไฟล์นั้นจึงจะอ่านอะไรได้ การกู้คืนให้คุณข้อความที่ปิดผนึกไว้ ไม่ได้ให้กุญแจ",
  "restore.new.meta": "{fp} · {n} ข้อความ",
  "restore.new.go": "กู้คืนที่เก็บนี้",
  "restore.same.t": "ที่เก็บเดียวกัน — จะเพิ่มข้อความอีก {n} ข้อความ",
  "restore.same.t.one": "ที่เก็บเดียวกัน — จะเพิ่มข้อความอีก 1 ข้อความ",
  "restore.same.t.none": "ที่เก็บเดียวกัน — ไม่มีอะไรใหม่ในไฟล์นี้",
  "restore.same.b": "ไฟล์นี้เป็นของที่เก็บที่มีอยู่แล้วในเครื่องนี้ ในไฟล์มี {new} รายการที่ยังไม่มีที่นี่ ส่วนอีก {old} รายการมีอยู่แล้วและจะไม่ถูกแตะต้อง ไม่มีสิ่งใดในเครื่องนี้ถูกแทนที่",
  "restore.same.new": "ใหม่ — จะถูกเพิ่มเข้ามา",
  "restore.same.old": "มีอยู่แล้ว — ไม่ถูกแตะต้อง",
  "restore.same.go": "เพิ่มข้อความใหม่",
  "restore.bad": "ไฟล์นี้ไม่ใช่ไฟล์สำรองของ Dying Message หรือถูกตัดทอนไป ไม่มีอะไรถูกเปลี่ยนแปลง",
  "restore.added": "เพิ่มข้อความแล้ว {n} ข้อความ",
  "restore.added.one": "เพิ่มข้อความแล้ว 1 ข้อความ",
  "restore.full.t": "ไม่มีที่ว่างสำหรับที่เก็บเพิ่ม",
  "restore.full.b": "ไฟล์นี้เป็นที่เก็บที่ยังไม่มีในเครื่องนี้ แต่เครื่องนี้มีที่เก็บอยู่ {n} แห่งแล้ว ซึ่งเป็นจำนวนสูงสุด ให้ลบที่เก็บแห่งหนึ่งออกจากหน้าตั้งค่าของมันก่อน แล้วจึงกู้คืนไฟล์นี้",

  // ---- H: settings
  "set.relock.1": "1 นาที",
  "set.relock.2": "2 นาที",
  "set.relock.5": "5 นาที",
  "set.relock.manual": "จนกว่าฉันจะสั่งล็อก",
  "set.relock.manual.note": "ที่เก็บจะเปิดอยู่จนกว่าคุณจะกดล็อกหรือออกจากแอป หากคุณวางโทรศัพท์ลงขณะที่ยังเปิดอยู่ มันก็จะเปิดอยู่อย่างนั้น",
  "set.theme.light": "สว่าง",
  "set.theme.dark": "มืด",
  "set.rekey.needbackup": "กรุณาสำรองข้อมูลก่อน ปุ่มนี้จะใช้ได้เมื่อมีไฟล์สำรองของวันนี้แล้ว",
  "set.rekey.new": "วลีรหัสผ่านใหม่",
  "set.rekey.confirm": "พิมพ์วลีรหัสผ่านใหม่อีกครั้ง",
  "set.rekey.nomatch": "ทั้งสองช่องไม่ตรงกัน",
  "set.rekey.go": "ปิดผนึกทุกข้อความใหม่",
  "set.rekey.done": "เสร็จแล้ว ทุกข้อความถูกปิดผนึกด้วยวลีรหัสผ่านใหม่ และลายนิ้วมือเปลี่ยนเป็น {fp} กรุณาสำรองข้อมูลใหม่ทันที เพราะไฟล์สำรองเดิมของคุณต้องใช้วลีรหัสผ่านเดิม",

  // ---- destructive confirmations
  "confirm.type": "พิมพ์ {phrase} เพื่อยืนยัน",
  "confirm.delete.entry.t": "ลบข้อความที่ {n}",
  "confirm.delete.entry.b": "ข้อความนี้จะถูกลบออกจากเครื่องนี้ หากมีอยู่ในไฟล์สำรองที่คุณเก็บไว้ สำเนานั้นจะยังอยู่ แต่ถ้าไม่มี ก็คือหายไปและเรียกกลับมาไม่ได้",
  "confirm.delete.entry.go": "ลบอย่างถาวร",
  "confirm.delete.entry.phrase": "ลบข้อความที่ {n}",
  "confirm.remove.vault.t": "ลบที่เก็บนี้",
  "confirm.remove.vault.b": "ข้อความที่ปิดผนึกไว้ทุกข้อความในที่เก็บนี้จะถูกลบ พร้อมกับกุญแจสาธารณะของที่เก็บ ไฟล์สำรองพร้อมกับคำ 24 คำของคุณคือทางเดียวที่จะได้เห็นมันอีก",
  "confirm.remove.vault.go": "ลบที่เก็บนี้ทิ้ง",

  // ---- C4: printed plate template
  "print.how": "ตอกช่องที่มีเครื่องหมายในแต่ละแถว ค่าน้ำหนักของช่องที่ทำเครื่องหมายไว้รวมกันได้เท่ากับตัวเลขในคอลัมน์สุดท้าย ซึ่งคือตำแหน่งของคำในรายการ BIP39 โดยนับเริ่มจาก 1 ลำดับของแถวสำคัญไม่แพ้ตัวคำ",
  "print.burn": "เผาหรือทำลายแผ่นกระดาษนี้เมื่อตอกแผ่นเสร็จแล้ว กระดาษในลิ้นชักคือสาเหตุที่พบบ่อยที่สุดที่ทำให้ชุดคำสูญหาย และเป็นทางที่พบบ่อยที่สุดที่ทำให้คนผิดคนได้พบมัน",
  "print.nopass": "แผ่นนี้ไม่มีวลีรหัสผ่านอยู่ หากคุณตั้งไว้ นั่นคือความลับคนละชิ้นและต้องเก็บไว้ที่อื่น",
  "print.legend": "ช่องทึบ = ตอก ช่องว่าง = เว้นไว้",
  "print.go": "พิมพ์แผ่นนี้",
  "print.blocked": "การพิมพ์ถูกปิดไว้ในหน้านี้ เพราะหน้าเว็บจะมีสิ่งที่ไม่ควรอยู่บนกระดาษติดไปด้วย แบบฟอร์มสำหรับตอกแผ่นคือหน้าเดียวที่แอปนี้พิมพ์",

  // ---- I: guide
  "guide.what.b2": "ตอนที่ตั้งค่าแอป แอปได้สร้างคำภาษาอังกฤษธรรมดายี่สิบสี่คำเรียงตามลำดับที่ตายตัว คำเหล่านั้นคือกุญแจ ทุกสิ่งที่เขียนไว้ที่นี่ถูกล็อกด้วยคำเหล่านั้น และไม่มีสิ่งอื่นใดปลดล็อกได้ คำเหล่านี้ไม่ได้ถูกเก็บไว้ในแอปหรือบนเซิร์ฟเวอร์ใด เพราะไม่มีเซิร์ฟเวอร์เลย คำเหล่านั้นมีอยู่เฉพาะที่ที่ถูกจดไว้เท่านั้น",
  "guide.what.b3": "ดังนั้นแอปนี้จะถูกเปิด ถูกเปิดดู หรือแม้แต่ถูกคัดลอกไปก็ได้ โดยไม่เปิดเผยอะไรเลย ใครถือคำเหล่านั้นไว้ คนนั้นถือทุกอย่าง",
  "guide.cannot.t": "สิ่งที่แอปนี้ทำไม่ได้",
  "guide.cannot.b": "แอปช่วยอะไรไม่ได้เลยหากคำหายไป นี่คือส่วนที่คนมักไม่เชื่อจนกว่าจะเกิดขึ้นจริง จึงควรพูดให้ชัด ไม่มีลิงก์รีเซ็ต ไม่มีอีเมลติดต่อ ไม่มีประตูหลัง และไม่มีเทคนิคแยบยลใด ๆ ชุดคำที่หายไปหมายความว่าข้อความจะถูกล็อกไว้ตลอดกาล",
  "guide.cannot.1": "กู้คืนชุดคำที่หายไป หรือส่วนใดส่วนหนึ่งของมัน ไม่ได้",
  "guide.cannot.2": "บอกไม่ได้ว่าคำเหล่านั้นคืออะไร หรือคุณใส่ผิดไปกี่คำ",
  "guide.cannot.3": "ส่งข้อความถึงใครไม่ได้ ทั้งตอนนี้และในอนาคต ต้องมีคนได้รับชุดคำไป",
  "guide.cannot.4": "ไม่มีทางรู้ว่าคุณเสียชีวิตแล้ว ไม่มีสิ่งใดที่นี่ถูกกระตุ้นด้วยเหตุการณ์ใด",
  "guide.cannot.5": "อยู่รอดไม่ได้หากแอปถูกลบออกจากเครื่อง เว้นแต่จะมีไฟล์สำรองอยู่ที่อื่น",
  "guide.keep.t": "การเก็บรักษาคำทั้งยี่สิบสี่คำ",
  "guide.keep.b": "มีสองอย่างที่ผิดพลาดได้ คือคำถูกทำลาย หรือคำไปอยู่ในมือคนผิด ต้องป้องกันทั้งสองอย่าง และพึงจำไว้ว่าการสูญหายส่วนใหญ่เป็นเรื่องธรรมดาน่าเบื่อ เช่น น้ำท่วม การย้ายบ้าน หรือญาติที่หวังดีมาเก็บกวาดลิ้นชัก",
  "guide.keep.1.t": "เขียนด้วยมือลงกระดาษ สองชุด",
  "guide.keep.1.b": "สองสำเนาในสองอาคาร กระดาษอาจดูล้าสมัย แต่มันอยู่ได้นานกว่าทุกรูปแบบการเก็บข้อมูลที่ถูกคิดค้นขึ้นมาหลังจากนั้น",
  "guide.keep.2.t": "ดีกว่านั้น คือตอกลงบนแผ่นโลหะ",
  "guide.keep.2.b": "แอปพิมพ์แบบฟอร์มสำหรับงานนี้ให้ได้ โลหะทนไฟและทนน้ำ ส่วนกระดาษไม่ทน และฮาร์ดดิสก์ก็ไม่ทนเช่นกัน",
  "guide.keep.3.t": "รักษาลำดับและหมายเลขไว้",
  "guide.keep.3.b": "คำที่ถูกแต่อยู่ผิดตำแหน่งคือคำที่ผิด ให้ใส่หมายเลขทุกบรรทัดตั้งแต่ 1 ถึง 24",
  "guide.keep.4.t": "บอกให้ใครสักคนรู้ว่ามันมีอยู่",
  "guide.keep.4.b": "ความล้มเหลวที่พบบ่อยที่สุดไม่ใช่การถูกขโมย แต่คือการที่ไม่มีใครรู้ว่าลิ้นชักนั้นสำคัญ แล้วมันถูกเก็บกวาดไปพร้อมกับของอื่นทั้งหมด",
  "guide.keep.never": "อย่าถ่ายภาพคำเหล่านี้ อย่าพิมพ์ลงแอปจดบันทึก และอย่าส่งอีเมลถึงตัวเอง สิ่งใดที่อยู่บนโทรศัพท์หรือคอมพิวเตอร์ย่อมถูกสำรองไว้ที่ใดที่หนึ่งที่คุณลืมไปแล้ว และถูกอ่านโดยบางสิ่งที่คุณไม่เคยตกลงด้วย",
  "guide.split.t": "การแบ่งความลับให้คนสองคน",
  "guide.split.b1": "หากตั้งวลีรหัสผ่านไว้ ก็จะมีความลับสองชิ้นแทนที่จะเป็นชิ้นเดียว และต้องใช้ทั้งสองชิ้น นั่นทำให้คุณมอบคำยี่สิบสี่คำให้คนหนึ่ง และมอบวลีรหัสผ่านให้อีกคนหนึ่งได้",
  "guide.split.b2": "ทั้งสองคนอ่านอะไรตามลำพังไม่ได้ แต่เมื่ออยู่ด้วยกันก็อ่านได้ เป็นวิธีบอกว่า “สองคนนี้ควรเห็นพ้องกันก่อนที่สิ่งนี้จะถูกเปิด” โดยไม่ต้องพึ่งความปรารถนาดีของใคร",
  "guide.split.b3": "ราคาของมันมีจริง หากครึ่งใดครึ่งหนึ่งหายไป ข้อความก็หายไปด้วย และคุณได้เพิ่มจำนวนหนทางที่เรื่องนั้นจะเกิดขึ้นเป็นสองเท่า ควรบอกทั้งสองคนว่ามีอีกฝ่ายอยู่ และเขียนไว้ที่ใดที่หนึ่งตามปกติ เช่น ไว้กับพินัยกรรมของคุณ ว่าต้องใช้สองส่วนและใครถือส่วนใด ตัวความลับต้องเป็นความลับ แต่ข้อตกลงนี้ไม่ควรเป็น",
  "guide.multi.t": "การใช้มากกว่าหนึ่งเครื่อง",
  "guide.multi.b": "ไม่มีการซิงก์ข้อมูล เพราะการซิงก์ต้องใช้เซิร์ฟเวอร์ แต่คุณใส่ชุดคำเดียวกันบนเครื่องที่สอง แล้วย้ายไฟล์สำรองข้ามไปได้",
  "guide.multi.1": "ติดตั้งแอปบนเครื่องที่สอง แล้วใส่คำยี่สิบสี่คำและวลีรหัสผ่านชุดเดียวกัน",
  "guide.multi.2": "ทำไฟล์สำรองบนเครื่องแรก แล้วย้ายข้ามไปด้วยวิธีใดก็ได้ ไฟล์ถูกเข้ารหัสไว้แล้ว จะส่งทางอีเมลหรือผ่านไดรฟ์บนคลาวด์ก็ได้",
  "guide.multi.3": "กู้คืนไฟล์นั้นบนเครื่องที่สอง แอปจะบอกว่ากำลังเพิ่มข้อความกี่ข้อความ",
  "guide.multi.after": "จากนั้นทั้งสองเครื่องจะถือที่เก็บเดียวกัน การเขียนบนเครื่องหนึ่งจะยังไม่ปรากฏบนอีกเครื่อง จนกว่าคุณจะย้ายไฟล์สำรองข้ามไปอีกครั้ง จึงควรตัดสินใจว่าเครื่องไหนคือเครื่องที่คุณใช้เขียนจริง",
  "guide.heirs.t": "หากมีใครมอบคำเหล่านี้ไว้ให้คุณ",
  "guide.heirs.b": "มีคนเขียนอะไรบางอย่างถึงคุณ และจัดเตรียมไว้ให้คุณอ่านได้ ไม่ต้องรีบ ข้อความจะยังอยู่ และไม่มีอะไรหมดอายุ อ่านส่วนนี้เมื่อคุณพร้อม",
  "guide.heirs.1.t": "หาแอปให้เจอ",
  "guide.heirs.1.b": "เป็นไอคอนบนโทรศัพท์ แท็บเล็ต หรือคอมพิวเตอร์ ชื่อ Dying Message แอปจะใช้งานจากที่อยู่เว็บเพียงอย่างเดียวไม่ได้ ต้องเป็นไอคอนที่ติดตั้งไว้ บนเครื่องที่ใช้เขียนข้อความ หรือบนเครื่องที่กู้คืนไฟล์สำรองไว้แล้ว",
  "guide.heirs.2.t": "กด “ปลดล็อกเพื่ออ่าน”",
  "guide.heirs.2.b": "แล้วพิมพ์คำยี่สิบสี่คำตามลำดับที่ได้รับมา หากคุณได้รับแผ่นโลหะแทนตัวคำ ให้เลือก “ตารางแผ่น” แล้วแตะช่องที่มีรอยตอกทีละแถว",
  "guide.heirs.3.t": "หากคุณได้รับวลีรหัสผ่านมาด้วย",
  "guide.heirs.3.b": "ให้พิมพ์ตามที่เขียนไว้ทุกตัวอักษร รวมถึงตัวพิมพ์ใหญ่และช่องว่าง โดยใส่ในช่องที่อยู่ใต้คำ",
  "guide.heirs.4.t": "หากคุณได้รับไฟล์มา",
  "guide.heirs.4.b": "ให้ติดตั้งแอปบนเครื่องใดก็ได้ เลือก “กู้คืน” แล้วเลือกไฟล์นั้น จากนั้นปลดล็อกด้วยคำตามขั้นตอนข้างต้น",
  "guide.heirs.5.t": "ไม่มีสิ่งใดที่คุณทำแล้วจะทำให้มันพัง",
  "guide.heirs.5.b": "คำที่ผิดจะถูกปฏิเสธเฉย ๆ คุณไม่สามารถทำให้ข้อความเสียหายหรือถูกลบได้ด้วยการลองผิดลองถูก",
  "guide.heirs.wait": "การรอสามถึงสิบวินาทีเมื่อกดเปิดเป็นเรื่องปกติ และเกิดขึ้นทุกครั้ง ไม่มีอะไรค้าง",
  "guide.stuck.t": "หากเปิดไม่ได้",
  "guide.stuck.b": "ให้ไล่ตรวจตามลำดับนี้ ไม่มีการจำกัดจำนวนครั้งที่ลอง และไม่มีการล็อกไม่ให้เข้า ใช้เวลาได้เท่าที่ต้องการ",
  "guide.stuck.1": "ตรวจลำดับ อ่านรายการของคุณตั้งแต่ 1 ถึง 24 แล้วเทียบกับหมายเลขบนหน้าจอ",
  "guide.stuck.2": "ตรวจตัวอักษรที่อาจอ่านผิด ลายมือ “rn” ดูเหมือน “m” ส่วน “l” กับ “1” มักสลับกัน แอปรับเฉพาะคำจริงจากรายการของมัน ตัวอักษรที่ผิดจึงมักแสดงให้เห็นทันที",
  "guide.stuck.3": "หากคุณมีแผ่นโลหะ ให้ตรวจว่าแผ่นใช้การนับแบบใด บางแผ่นนับเริ่มจาก 1 บางแผ่นเริ่มจาก 0 แอปมีสวิตช์สำหรับเรื่องนี้ และหากเลือกผิด คำทุกคำจะเลื่อนไปหมด",
  "guide.stuck.4": "ตรวจวลีรหัสผ่านว่ามีช่องว่างหลงเหลืออยู่ท้ายข้อความหรือไม่ หรือมีตัวพิมพ์ใหญ่ที่แป้นพิมพ์เติมให้เอง",
  "guide.stuck.5": "หากแอปบอกว่าชุดคำเป็นของที่เก็บอื่น แปลว่าคำถูกต้อง เพียงแต่มันเปิดที่เก็บอื่น ลองหาไฟล์สำรองอีกไฟล์ หรือเครื่องอื่น",
  "guide.foot": "แอปนี้ถูกสร้างขึ้นให้น่าเบื่อ และให้อยู่ได้นานกว่าคนที่สร้างมัน แอปไม่ส่งอะไรออกไป ไม่ขออะไรจากใคร และจะทำงานต่อไปได้โดยไม่ต้องเชื่อมต่ออินเทอร์เน็ต ตราบเท่าที่เครื่องที่ติดตั้งไว้ยังทำงานอยู่",

  // ---- screen-reader labels
  "sr.gridcell": "คำที่ {w} บิต {bit} {state}",
  "sr.punched": "ตอกแล้ว",
  "sr.notpunched": "ยังไม่ตอก",
  "sr.rowresolves": "คำที่ {w} ได้เป็น {word} ค่า {idx}",
  "sr.rowunset": "คำที่ {w} ยังไม่มีการตอก",
  "sr.wordfield": "คำที่ {n} จาก 24",
  "sr.inwordlist": "อยู่ในรายการคำ",
  "sr.notinwordlist": "ไม่อยู่ในรายการคำ",
  "sr.entry": "ข้อความที่ {n} ปิดผนึก ประมาณ {size} วันที่ {date}",
  "sr.entrybad": "ข้อความที่ {n} ไม่ตรงกับผนึก ประมาณ {size} วันที่ {date}",
  "sr.derive": "กำลังคำนวณกุญแจ ขั้นตอนนี้ใช้เวลาสามถึงสิบวินาทีและช้าโดยตั้งใจ ผ่านไปแล้ว {n} วินาที",
};
